<?php
/**
 * /var/www/html/frontend/runtime/giiant/49eb2de82346bc30092f584268252ed2
 *
 * @package default
 */


namespace backend\controllers;

/**
 * This is the class for controller "PayrollAdjustmentCodeController".
 */
class PayrollAdjustmentCodeController extends \backend\controllers\base\PayrollAdjustmentCodeController
{
    public function actionUpdate($code)
    {
        return parent::actionUpdate($code); // TODO: Change the autogenerated stub
    }

}
