<?php
/**
 * /var/www/html/backend/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 *
 * @var yii\web\View $this
 * @var common\models\AccessorialPay $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="accessorial-pay-form">

    <?php $form = ActiveForm::begin([
		'id' => 'AccessorialPay',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-danger',
		'fieldConfig' => [
			'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
			'horizontalCssClasses' => [
				'label' => 'col-sm-2',
				//'offset' => 'col-sm-offset-4',
				'wrapper' => 'col-sm-8',
				'error' => '',
				'hint' => '',
			],
		],
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


<!-- attribute office_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'office_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(common\models\Office::find()->all(), 'id', '_label'),
	[
		'prompt' => Yii::t('app', 'Select'),
		'disabled' => (isset($relAttributes) && isset($relAttributes['office_id'])),
	]
); ?>

<!-- attribute accessorial_rating_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'accessorial_rating_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(common\models\AccessorialRating::find()->all(), 'id', '_label'),
	[
		'prompt' => Yii::t('app', 'Select'),
		'disabled' => (isset($relAttributes) && isset($relAttributes['accessorial_rating_id'])),
	]
); ?>

<!-- attribute rate_each -->
			<?php echo $form->field($model, 'rate_each')->textInput() ?>

<!-- attribute inactive -->
			<?php echo $form->field($model, 'inactive')->checkbox() ?>

<!-- attribute calc_by -->
			<?php echo $form->field($model, 'calc_by')->dropDownList(\common\enums\CalculateBy::getUiEnums(), ['prompt' => Yii::t('app', 'Select')])?>

<!-- attribute basis -->
			<?php echo $form->field($model, 'basis')->dropDownList(\common\enums\BasisType::getUiEnums(), ['prompt' => Yii::t('app', 'Select')])?>
        </p>
        <?php $this->endBlock(); ?>

        <?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => Yii::t('app', 'AccessorialPay'),
				'content' => $this->blocks['main'],
				'active'  => true,
			],
		]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
