<?php
/**
 * /var/www/html/frontend/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use common\enums\LoadStatus;
use common\models\DispatchAssignment;
use common\models\State;
use common\widgets\DataTables\DataColumn;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Tabs;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/**
 *
 * @var yii\web\View $this
 * @var common\models\Trailer $model
 * @var yii\widgets\ActiveForm $form
 */
?>
<section class="edit-form trailer-form">

    <?php $form = ActiveForm::begin([
		'id' => 'Trailer',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-danger',
		'fieldConfig' => Yii::$app->params['activeForm']['horizontalFormConfig'],
	]
);
$this->beginBlock('main');
?>
    <div class="row">
        <div class="col-lg-6">
            <?php echo $form->field($model, 'trailer_no')->textInput(['maxlength' => true]); ?>
			<!-- attribute type -->
			<?php echo $form->field($model, 'type')->dropDownList(
			    ArrayHelper::map(\common\models\TrailerType::find()->all(), 'type', '_label'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['type']))
                ]
            ) ?>

			<!-- attribute year -->
			<?php echo $form->field($model, 'year')->textInput(['type' => 'number']) ?>

			<!-- attribute make -->
			<?php echo $form->field($model, 'make')->textInput(['maxlength' => true]) ?>

			<!-- attribute model -->
			<?php echo $form->field($model, 'model')->textInput(['maxlength' => true]) ?>

			<!-- attribute tare -->
			<?php echo $form->field($model, 'tare')->textInput(['type' => 'number']) ?>

            <!-- attribute length -->
            <?php echo $form->field($model, 'length')->textInput(['type' => 'number']) ?>

            <!-- attribute height -->
            <?php echo $form->field($model, 'height')->textInput(['type' => 'number']) ?>

            <!-- attribute in_svc -->
            <?php echo $form->field($model, 'in_svc')->textInput(['type' => 'date']) ?>

            <!-- attribute serial -->
            <?php echo $form->field($model, 'serial')->textInput(['maxlength' => true]) ?>

            <div class="form-group row">
                <label class="col-sm-2"><?= $model->getAttributeLabel('license').', '.Yii::t('app','State') ?></label>
                <!-- attribute license -->
                <?php echo $form->field($model, 'license', ['template' => '<div class="col-6">{input}{error}{hint}</div>', 'options' => ['tag' => false]])
                    ->textInput(['maxlength' => true]) ?>
                <!-- attribute license_state_id -->
                <?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
                $form->field($model, 'license_state_id', ['template' => '<div class="col-2">{input}{error}{hint}</div>', 'options' => ['tag' => false]])->dropDownList(
                    \yii\helpers\ArrayHelper::map(common\models\State::find()->all(), 'id', '_label'),
                    [
                        'prompt' => 'Select',
                        'disabled' => (isset($relAttributes) && isset($relAttributes['license_state_id'])),
                    ]
                ); ?>
            </div>

            <!-- attribute carb_id -->
            <?php echo $form->field($model, 'carb_id')->textInput(['maxlength' => true]) ?>

            <!-- attribute office_id -->
            <?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'office_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(common\models\Office::find()->all(), 'id', '_label'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['office_id'])),
                ]
            ); ?>

			<!-- attribute status -->
			<?php //echo $form->field($model, 'status')->textInput(['maxlength' => true]) ?>

        </div>
        <div class="col-lg">
            <!-- attribute notes -->
            <?php echo $form->field($model, 'notes')->textarea(['rows' => 6]) ?>
        </div>
    </div>
    <?php $this->endBlock(); ?>
    <?php $this->beginBlock('financial'); ?>
    <div class="row">
      <div class="col-12">
        <div class="form-fieldset">
          <span class="form-legend"><?= Yii::t('app', 'Ownership') ?></span>
          <div class="row">
            <div class="col">
                <?= $form->field($model, 'company_owned_leased')->dropDownList(\common\enums\CompanyOwnedLeased::getUiEnums(false), ['prompt' => Yii::t('app', 'Select')]) ?>
            </div>
            <div class="col">
                <?= $form->field($model, 'owned_by_carrier_id')->widget(\common\widgets\tdd\Dropdown::class, [
                    'displayColumnIndex' => 2,
                    'destAttribute' => [['owned_by_carrier_id' => 0, 'owned_by_customer_id' => 1, 'owned_by_vendor_id' => 2, 'owned_by_driver_id' => 3], 0, 1],
                    'grid' => [
                        'dataProvider' => new \yii\data\SqlDataProvider([
                            'sql' => \common\models\Carrier::find()
                                ->select(new \yii\db\Expression("t0.id,t0.name,t0.address_1,t0.address_2,t0.city,state_code,0 AS type"))
                                ->alias('t0')
                                ->leftJoin(State::tableName(), 't0.state_id=' . State::tableName() . '.id')
                                ->union(\common\models\Customer::find()
                                    ->select(new \yii\db\Expression("t0.id,t0.name,t0.address_1,t0.address_2,t0.city,state_code,1 AS type"))
                                    ->alias('t0')
                                    ->leftJoin(State::tableName(), 't0.state_id=' . State::tableName() . '.id')
                                )
                                ->union(\common\models\Vendor::find()
                                    ->select(new \yii\db\Expression("t0.id,t0.name,t0.address_1,t0.address_2,t0.city,state_code,2 AS type"))
                                    ->alias('t0')
                                    ->leftJoin(State::tableName(), 't0.state_id=' . State::tableName() . '.id')
                                )
                                ->union(\common\models\Driver::find()
                                    ->select(new \yii\db\Expression("t0.id,concat_ws(', ',t0.last_name,t0.first_name) AS name,t0.address_1,t0.address_2,t0.city,state_code,3 AS type"))
                                    ->alias('t0')
                                    ->leftJoin(State::tableName(), 't0.state_id=' . State::tableName() . '.id')
                                )->createCommand()->getRawSql()
                        ]),
                        'columns' => [
                            'type|visible=false|searchable=false',
                            'id|visible=false|searchable=false',
                            'name',
                            new DataColumn([
                                'title' => Yii::t('app', 'Address'),
                                'value' => function ($model) {
                                    return $model->address_1 ? $model->address_1 : $model->address_2;
                                }
                            ]),
                            'city',
                            new DataColumn([
                                'title' => Yii::t('app', 'St'),
                                'attribute' => 'state_code'
                            ]),
                            new DataColumn([
                                'title' => Yii::t('app', 'Type'),
                                'value' => function ($model) {
                                    $message = '';
                                    switch ($model->type) {
                                        case 0:
                                            $message = 'Carrier';
                                            break;
                                        case 1:
                                            $message = 'Customer';
                                            break;
                                        case 2:
                                            $message = 'Vendor';
                                            break;
                                        case 3:
                                            $message = 'Driver';
                                            break;
                                    }
                                    return Yii::t('app', $message);
                                }
                            ]),
                            new DataColumn([
                                'title' => Yii::t('app', 'Inactive'),
                                'value' => function ($model) {
                                    return '<input type="checkbox" class="editor-active" onclick="return false;">';
                                },
                                'className' => 'dt-body-center text-center',
                            ]),
                        ],
                        'order' => [[6, 'asc']]
                    ]
                ])->label(Yii::t('app', 'Owned By')) ?>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        <div class="form-fieldset">
          <span class="form-legend"><?= Yii::t('app', 'Purchase') ?></span>
          <?= $form->field($model, 'purchased_new')->checkbox(['template' => Yii::$app->params['activeForm']['noIndentCheckbox']['template']]) ?>
            <?= $form->field($model, 'purchase_date')->textInput(['type' => 'date']) ?>
            <?= $form->field($model, 'purchase_price')->textInput(['type' => 'number', 'min' => 0, 'step' => 1]) ?>
        </div>
      </div>
      <div class="col-6">
        <div class="form-fieldset">
          <span class="form-legend"><?= Yii::t('app', 'Physical Damage Insurance') ?></span>
            <?= $form->field($model, 'insured')->checkbox(['template' => Yii::$app->params['activeForm']['noIndentCheckbox']['template']]) ?>
            <?= $form->field($model, 'insured_date')->textInput(['type' => 'date']) ?>
            <?= $form->field($model, 'insured_value')->textInput(['type' => 'number', 'min' => 0, 'step' => 1]) ?>
            <?= $form->field($model, 'annual_premium')->textInput(['type' => 'number', 'min' => 0, 'step' => 1]) ?>
            <?= $form->field($model, 'depreciated_value')->textInput(['type' => 'number', 'min' => 0, 'step' => 1]) ?>
        </div>
      </div>
    </div>
    <?php /* ?>
    <div class="row">
      <div class="col-4">
        <div class="form-fieldset">
          <span class="form-legend"><?= Yii::t('app', 'Purchase') ?></span>
            <?= $form->field($model, 'purchased_new')->checkbox(['template' => Yii::$app->params['activeForm']['noIndentCheckbox']['template']]) ?>
            <?= $form->field($model, 'purchase_date')->textInput(['type' => 'date']) ?>
            <?= $form->field($model, 'purchase_price')->textInput(['type' => 'number', 'min' => 0, 'step' => 0.01]) ?>
        </div>
      </div>
      <div class="col-4">
        <div class="form-fieldset">
          <span class="form-legend"><?= Yii::t('app', 'Tax Info') ?></span>
            <?= $form->field($model, 'non_ifta')->checkbox(['template' => Yii::$app->params['activeForm']['noIndentCheckbox']['template']]) ?>
            <?= $form->field($model, 'ny_permit')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'ny_gross')->textInput(['type' => 'number']) ?>
          <hr>
            <?= $form->field($model, 'or_decl_wgt')->textInput(['type' => 'number']) ?>
            <?= $form->field($model, 'or_decl_axles')->dropdownList(common\enums\ORDeclAxle::getUiEnums(), ['prompt' => Yii::t('app', 'Select')]) ?>
        </div>
      </div>
      <div class="col-4">
        <div class="form-fieldset">
          <span class="form-legend"><?= Yii::t('app', 'Physical Damage Insurance') ?></span>
            <?= $form->field($model, 'insured')->checkbox(['template' => Yii::$app->params['activeForm']['noIndentCheckbox']['template']]) ?>
            <?= $form->field($model, 'insured_date')->textInput(['type' => 'date']) ?>
            <?= $form->field($model, 'insured_value')->textInput(['type' => 'number', 'min' => 0, 'step' => 0.01]) ?>
            <?= $form->field($model, 'annual_premium')->textInput(['type' => 'number', 'min' => 0, 'step' => 0.01]) ?>
            <?= $form->field($model, 'depreciated_value')->textInput(['type' => 'number', 'min' => 0, 'step' => 0.01]) ?>
        </div>
      </div>
    </div>
    <?php */ ?>
    <?php $this->endBlock(); ?>
    <?php echo Tabs::widget([
        'encodeLabels' => false,
        'items' => [
            [
                'label' => Yii::t('app', 'Info'),
                'content' => $this->blocks['main'],
                'active' => true,
            ],
            [
                'label' => Yii::t('app', 'Financial'),
                'content' => $this->blocks['financial'],
                'active' => false
            ]
        ]]); ?>
    <br/>
    <?php
    /** @var \common\models\TrackingLog $trackingRecord */
    $trackingRecord = $model->getTrackingLogs()->orderBy(['created_at' => SORT_DESC])->one();
    ?>
  <div class="row">
    <div class="col-12">
        <div class="form-fieldset">
          <span class="form-legend"><?= Yii::t('app', 'Status') ?></span>
          <div class="row">
            <div class="col-3">
              <div class="row">
                <div class="col-6 text-right"><?= Yii::t('app', 'Status') ?></div>
                <div class="col-6"><?= $model->status ?></div>
                <div class="col-6 text-right"><?= Yii::t('app', 'Date') ?></div>
                <div class="col-6"><?= $trackingRecord ? Yii::$app->formatter->asDate($trackingRecord->date, Yii::$app->params['formats'][1]) : '' ?></div>
                <div class="col-6 text-right"><?= Yii::t('app', 'Trip Type') ?></div>
                <div class="col-6">TL</div>
                <div class="col-6 text-right"><?= Yii::t('app', 'Load No') ?></div>
                <div class="col-6">
                  <?php
                  $loadNo = '';
                  /** @var DispatchAssignment $da */
                  $da = DispatchAssignment::find()
                      ->alias('da')
                      ->joinWith('load l')
                      ->where(new \yii\db\Expression(
                          '(l.status=:loadStatus1 OR l.status=:loadStatus2) AND (da.trailer_id=:trailerId OR da.trailer2_id=:trailerId)',
                          [':loadStatus1' => LoadStatus::ENROUTED, ':loadStatus2' => LoadStatus::DROPPED, ':trailerId' => $model->id]
                      ))
                      ->one();
                  if ($da) {
                      $loadNo = $da->load->id;
                  }
                  echo $loadNo;
                  ?>
                </div>
              </div>
            </div>
            <div class="col-3">
              <div class="row">
                <div class="col-6 text-right"><?= Yii::t('app', 'Location') ?></div>
                <div class="col-6">
                  <?php
                  if ($trackingRecord) {
                    echo sprintf(
                            '<span class="form-readonly-text">%s<br/>%s, %s %s</span>',
                            $trackingRecord->location->address,
                            $trackingRecord->location->city,
                            $trackingRecord->location->state ? $trackingRecord->location->state->state_code : '',
                            $trackingRecord->location->zip
                    );
                  }
                  ?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <?php echo $form->errorSummary($model); ?>
    <?php echo Html::submitButton('<i class="fas fa fa-check"></i> ' . ($model->isNewRecord ? 'Create' : 'Save'), ['id' => 'save-' . $model->formName(), 'class' => 'btn btn-success']); ?>
    <?php ActiveForm::end(); ?>
</section>
