services:
    - docker:19.03.1-dind

stages:
  - build_staging
  - deploy_staging

build_staging:
    stage: build_staging
    environment: staging
    only:
        - develop
    script:
        - docker build -f .docker/Dockerfile -t $REGISTRY/tms/app:staging --build-arg APP_ENV=staging .
        - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD $REGISTRY/tms/app:staging
        - docker push $REGISTRY/tms/app:staging

deploy_staging:
  stage: deploy_staging
  environment: staging
  only:
    - develop
  script:
    - apk update
    - apk add openssh
    - echo "-----BEGIN RSA PRIVATE KEY-----" > key.pem
    - echo $SSH_KEY >> key.pem
    - echo "-----END RSA PRIVATE KEY-----" >> key.pem
    - chmod 400 key.pem
    - scp -i key.pem -o StrictHostKeyChecking=no .docker/docker-compose-staging.yml ubuntu@tms.jafton.com:~/tms_data/docker-compose.yml
    - scp -i key.pem -o StrictHostKeyChecking=no .docker/staging.env ubuntu@tms.jafton.com:~/tms_data/
    - ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@tms.jafton.com 'cd tms_data && docker login --username '$DOCKER_USERNAME' --password '$DOCKER_PASSWORD' '$REGISTRY'/tms/app:staging && docker pull '$REGISTRY'/tms/app:staging && docker compose -p tms stop && docker compose -p tms up --remove-orphans --detach'
    - rm key.pem
