<?php
/**
 * /var/www/html/backend/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
 *
 * @var yii\web\View $this
 * @var \backend\models\ProfileForm $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin([
		'id' => 'User',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-danger',
		'fieldConfig' => [
			'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
			'horizontalCssClasses' => [
				'label' => 'col-sm-2',
				//'offset' => 'col-sm-offset-4',
				'wrapper' => 'col-sm-8',
				'error' => '',
				'hint' => '',
			],
		],
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>

<!-- attribute email -->
			<?php echo $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

<!-- attribute password -->
            <?php echo $form->field($model, 'password')->textInput(['maxlength' => true]) ?>

<!-- attribute department_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'department_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(common\models\Department::find()->all(), 'id', '_label'),
	[
		'prompt' => Yii::t('app', 'Select'),
		'disabled' => (isset($relAttributes) && isset($relAttributes['department_id'])),
	]
); ?>

<!-- attribute default_office_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'default_office_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(common\models\Office::find()->all(), 'id', '_label'),
	[
		'prompt' => Yii::t('app', 'Select'),
		'disabled' => (isset($relAttributes) && isset($relAttributes['default_office_id'])),
	]
); ?>

<!-- attribute agent_and_subject_to_agent_rules -->
			<?php echo $form->field($model, 'agent_and_subject_to_agent_rules')->checkbox([], false) ?>

<!-- attribute can_access_dispatch_data_from_all_offices -->
			<?php echo $form->field($model, 'can_access_dispatch_data_from_all_offices')->checkbox([], false) ?>

        </p>
        <?php $this->endBlock(); ?>

        <?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => Yii::t('models', 'User'),
				'content' => $this->blocks['main'],
				'active'  => true,
			],
		]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->getUser()->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
