<?php
/**
 * /var/www/html/frontend/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */

use common\models\Customer;
use common\widgets\tdd\Dropdown;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Tabs;
use yii\data\ArrayDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use common\widgets\DataTables\DataColumn;

/**
 *
 * @var yii\web\View $this
 * @var Customer $model
 * @var \common\models\CustomerContactNote[] $contactNotes
 * @var \frontend\forms\CustomerContactNote[] $contactNotesForms
 */

$prompt = Yii::t('app', 'Select');
?>
<section class="edit-form customer-form">
    <?php $form = ActiveForm::begin([
            'id' => 'Customer',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-danger',
            'fieldConfig' =>  Yii::$app->params['activeForm']['horizontalFormConfig'],
        ]
    );

    $this->beginBlock('company');
    ?>
    <div class="row">
        <div class="col-lg-6">

            <!-- attribute name -->
            <?php echo $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

            <!-- attribute address_1 -->
            <?php echo $form->field($model, 'address_1')->textInput(['maxlength' => true]) ?>

            <!-- attribute address_2 -->
            <?php echo $form->field($model, 'address_2')->textInput(['maxlength' => true]) ?>

            <div class="form-group row">
                <label class="col-sm-2">
                    <?= $model->getAttributeLabel('city').', '.$model->getAttributeLabel('state_id').', '.$model->getAttributeLabel('zip') ?>
                </label>

                <!-- attribute city -->
                <?= $form->field($model, 'city', ['template' => '<div class="col-4">{input}{error}{hint}</div>', 'options' => ['tag' => false]])
                    ->textInput(['maxlength' => true, 'placeholder' => Yii::t('app', 'City')])
                ?>

                <!-- attribute state_id -->
                <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
                $form->field($model, 'state_id', ['options' => ['tag' => false], 'template' => '<div class="col-2">{input}{error}{hint}</div>',])
                    ->dropDownList(
                        ArrayHelper::map(common\models\State::find()->all(), 'id', '_label'),
                        [
                            'prompt' => Yii::t('app', 'State'),
                            'disabled' => (isset($relAttributes) && isset($relAttributes['state_id'])),
                        ]
                    )->label(false); ?>

                <!-- attribute zip -->
                <?= $form->field($model, 'zip', ['template' => '<div class="col-2">{input}{error}{hint}</div>', 'options' => ['tag' => false]])
                    ->textInput(['placeholder' => Yii::t('app', 'Zip')]) ?>
            </div>

            <!-- attribute main_phone -->
            <?php echo $form->field($model, 'main_phone')->textInput(['maxlength' => true]) ?>

            <!-- attribute main_800 -->
            <?php echo $form->field($model, 'main_800')->textInput(['maxlength' => true]) ?>

            <!-- attribute main_fax -->
            <?php echo $form->field($model, 'main_fax')->textInput(['maxlength' => true]) ?>

        </div>

        <div class="col-lg">

            <!-- attribute disp_contact -->
            <?php echo $form->field($model, 'disp_contact')->textInput(['maxlength' => true]) ?>

            <!-- attribute ap_contact -->
            <?php echo $form->field($model, 'ap_contact')->textInput(['maxlength' => true]) ?>

            <!-- attribute other_contact -->
            <?php echo $form->field($model, 'other_contact')->textInput(['maxlength' => true]) ?>

            <!-- attribute account_no -->
            <?php echo $form->field($model, 'account_no')->textInput(['maxlength' => true]) ?>

            <!-- attribute federal_id -->
            <?php echo $form->field($model, 'federal_id')->textInput(['maxlength' => true]) ?>

            <!-- attribute mc_id -->
            <?php echo $form->field($model, 'mc_id')->textInput(['maxlength' => true]) ?>

            <!-- attribute scac -->
            <?php echo $form->field($model, 'scac')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-lg-12">
            <!-- attribute notes -->
            <?php echo $form->field($model, 'notes')->textarea(['rows' => 6]) ?>
        </div>
    </div>
    <?php $this->endBlock(); ?>

    <?php $this->beginBlock('contacts'); ?>
    <?php
    $grid = \common\widgets\DataTables\Grid::widget([
        'dataProvider' => new ArrayDataProvider(['modelClass' => \common\models\CustomerContactNote::class]),
        'ajax' => Url::toRoute(['contact-notes', 'id' => $model->id+0]),
        'columns' => [
            'next_contact',
            'code',
            'notes'
        ],
        'cssClass' => 'w-100'
    ]);
    $this->params['modals'] = [[
        'id' => 'customer-notes-modal',
        'dialogCssClass' => 'modal-lg',
        'title' => Yii::t('app', 'Customer Notes'),
        'toolbar' => '<button class="btn btn-link js-ajax-modal" data-tooltip="tooltip" data-url="' . Url::toRoute(['create-contact-note', 'id' => $model->id]) . '" data-placement="top" title="' . Yii::t('app', 'Input Note') . '"><i class="fas fa-plus"></i></button>',
        'content' => $grid,
        'options' => [
            'saveButton' => false
        ]
    ]];
    ?>
    <div class="clearfix">
        <button data-url="<?= Url::toRoute(['contact-form', 'customer' => $model->id]) ?>" type="button" class="btn btn-sm btn-secondary float-right js-ajax-modal">
            <i class="fas fa fa-plus"></i> <?=Yii::t('app', 'Add')?>
        </button>
    </div>
    <br/>
    <?php $customerId = $model->id; ?>
    <?= yii\grid\GridView::widget([
        'dataProvider' => new ArrayDataProvider([
            'allModels' => $model->customerContacts,
        ]),
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'contact_name',
            [
                'attribute' => 'department.name',
                'label' => Yii::t('app', 'Department'),
            ],
            [
                'attribute' => 'direct_line',
                'label' => Yii::t('app', 'Phone'),
            ],
            'email',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}',
                'buttons' => [
                    'update' => function($name, $model, $key) use ($customerId) {
                        return Html::a('<i class="fas fa-pencil-alt" aria-hidden="true"></i>', '#', [
                            'class' => 'js-ajax-modal',
                            'data-url' => Url::toRoute(['contact-form', 'id' => $model->id, 'customer' => $customerId])
                        ]);
                    },
                    'delete' => function($name, $model, $key) use ($customerId) {
                        return Html::a('<i class="fas fa-trash" aria-hidden="true"></i>',
                            ['contact-delete', 'id' => $model->id, 'customer' => $customerId],
                            [
                                'data' => [
                                    'confirm' => Yii::t('app', 'Are you sure to delete this contact?'),
                                    'method' => 'post'
                                ]
                            ]
                        );
                    }
                ],
            ],
        ],
    ]); ?>
    <hr/>
    <?php $this->endBlock(); ?>
    <?php $this->beginBlock('defaults'); ?>
    <div class="row">
        <div class="col-4">
            <div class="form-fieldset">
                <span class="form-legend"><?= Yii::t('app', 'Rating') ?></span>
                <?= $form->field($model, 'rate_source')->dropdownList(
                    \common\enums\RateSource::getUiEnums(), 
                    ['prompt' => Yii::t('app', 'Select')]
                 ) ?>
                <?= $form->field($model, 'acc_matrix_id')->dropdownList(
                        ArrayHelper::map(\common\models\AccessorialMatrix::find()->orderBy(['matrix_no' => SORT_ASC])->all(), 'id', 'matrix_no'),
                        ['prompt' => $prompt]
                ) ?>
                <?= $form->field($model, 'discount')->textInput() ?>
            </div>
        </div>
        <div class="col-8">
            <div class="form-fieldset">
                <span class="form-legend"><?= Yii::t('app', 'Credit') ?></span>
                <div class="row">
                    <div class="col">
                        <?= $form->field($model, 'rating')->textInput(['maxlength' => true]) ?>
                        <?= $form->field($model, 'agency')->textInput(['maxlength' => true]) ?>
                        <?= $form->field($model, 'approved_by')->textInput() ?>
                        <?= $form->field($model, 'terms')->dropdownList(
                            ArrayHelper::map(\common\models\PaymentTermCode::find()->orderBy(['id' => SORT_ASC])->all(), 'id', 'description'),
                            ['prompt' => $prompt]
                        ) ?>
                        <?= $form->field($model, 'limit')->textInput() ?>
                        <?= $form->field($model, 'credit_hold')->checkbox() ?>
                    </div>
                    <div class="col">
                        <?= $form->field($model, 'bond')->checkbox() ?>
                        <?= $form->field($model, 'expires')->textInput(['type' => 'date']) ?>
                        <?= $form->field($model, 'number')->textInput(['maxlength' => true]) ?>
                        <?= $form->field($model, 'bank')->textarea(['rows' => 6]) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <div class="form-fieldset">
                <span class="form-legend"><?= Yii::t('app', 'Mileage') ?></span>
                <?= $form->field($model, 'system')->dropdownList(\common\enums\System::getUiEnums(), ['prompt' => Yii::t('app', 'Select')]) ?>
                <?= $form->field($model, 'calc_by')->dropdownList(\common\enums\CustomerCalcBy::getUiEnums(), ['prompt' => Yii::t('app', 'Select')]) ?>
            </div>
        </div>
        <div class="col-5">
            <div class="form-fieldset">
                <span class="form-legend"><?= Yii::t('app', 'Salesman') ?></span>
                <?= $form->field($model, 'salesman_1')->textInput() ?>
                <?= $form->field($model, 'pay_type_1')->dropdownList(\common\enums\CustomerPayType::getUiEnums(), ['prompt' => Yii::t('app', 'Select')]) ?>
                <?= $form->field($model, 'rate_1')->textInput() ?>
                <?= $form->field($model, 'salesman_2')->textInput() ?>
                <?= $form->field($model, 'pay_type_2')->dropdownList(\common\enums\CustomerPayType::getUiEnums(), ['prompt' => Yii::t('app', 'Select')]) ?>
                <?= $form->field($model, 'rate_2')->textInput() ?>
            </div>
        </div>
        <div class="col-3">
            <div class="form-fieldset">
                <span class="form-legend"><?= Yii::t('app', 'Options') ?></span>
                <?= $form->field($model, 'mail_list')->checkbox() ?>
                <?= $form->field($model, 'send_210')->checkbox() ?>
                <?= $form->field($model, 'send_214')->checkbox() ?>
            </div>
        </div>
    </div>
    <?php $this->endBlock(); ?>
    <?php $this->beginBlock('billing'); ?>
    <div class="row">
        <div class="col-5">
            <div class="row">
                <div class="form-fieldset">
                    <span class="form-legend"><?= Yii::t('app', 'Invoicing Options') ?></span>
                    <?= $form->field($model, 'other_bill_to')->widget(Dropdown::class, [
                        'items' => Customer::find()->where(['<>', 'id', $model->id])->all(),
                        'modelClass' => Customer::class,
                        'lookupColumnIndex' => 0,
                        'displayColumnIndex' => 1,
                        'grid' => [
                            'columns' => [
                                'id|visible=false|searchable=false',
                                'name',
                                new DataColumn([
                                    'title' => Yii::t('app', 'Address'),
                                    'value' => function ($model) {
                                        /** @var Customer $model */
                                        return trim($model->address_1 . ' ' . $model->address_2);
                                    }
                                ]),
                                'city',
                                new DataColumn([
                                    'title' => Yii::t('app', 'St'),
                                    'value' => function ($model) {
                                        /** @var Customer $model */
                                        if ($rel = $model->state) {
                                            return $rel->state_code;
                                        }

                                        return '';
                                    }
                                ]),
                                new DataColumn([
                                    'title' => Yii::t('app', 'Inactive'),
                                    'value' => function ($model) {
                                        /** @var Customer $model */

                                        return '<input type="checkbox" class="editor-active" onclick="return false;">';
                                    },
                                    'className' => 'dt-body-center text-center',
                                    'searchable' => false,
                                    'orderable' => true
                                ]),
                            ],
                            'order' => [[1, 'asc']]
                        ],
                    ]) ?>

                    <?= $form->field($model, 'invoice_style')->dropdownList(
                        \common\enums\InvoiceStyle::getUiEnums(),
                        ['prompt' => $prompt]
                    ) ?>

                    <?= $form->field($model, 'invoicing_method')->dropdownList(
                        \common\enums\InvoicingMethod::getUiEnums(),
                        ['prompt' => $prompt]
                    ) ?>

                    <?= $form->field($model, 'invoicing_email')->textInput(['maxlength' => true]) ?>

                    <?= $form->field($model, 'send_invoice_copies_to_invoicing_contacts')->checkbox() ?>

                    <?= $form->field($model, 'send_invoices_as_pdf_attachments')->checkbox() ?>

                    <?= $form->field($model, 'factor_invoices_for_this_customer')->checkbox() ?>

                    <?= $form->field($model, 'hide_load_mileages_on_invoices')->checkbox() ?>
                </div>
                <div class="form-fieldset">
                    <span class="form-legend"><?= Yii::t('app', 'Print On Every Invoice') ?></span>
                    <?php for ($i = 1; $i <= 5; $i++) echo $form->field($model, "line_$i")->textInput(['maxlength' => true])->label(false); ?>
                </div>
            </div>
        </div>
        <div class="col-7">
            <div class="form-fieldset">
                <span class="form-legend"><?= Yii::t('app', 'Documentation Requirements') ?></span>
                <?= $form->field($model, 'pre_billing_allowed_no_backup_required')->checkbox() ?>
                <?= $form->field($model, 'send_all_load_scans_with_each_invoice')->checkbox() ?>
                <?= $form->field($model, 'original_documents_required')->checkbox() ?>
                <span class="form-hr-text"><?= Yii::t('app', 'Backup Required With Every Invoice') ?></span>
                <div class="row">
                    <div class="col">
                        <?= $form->field($model, 'bill_of_lading')->checkbox() ?>
                        <?= $form->field($model, 'delivery_receipt')->checkbox() ?>
                        <?= $form->field($model, 'purchase_order')->checkbox() ?>
                        <?= $form->field($model, 'transport_agreement')->checkbox() ?>
                        <?= $form->field($model, 'interchanges')->checkbox() ?>
                    </div>
                    <div class="col">
                        <?= $form->field($model, 'packing_slip')->checkbox() ?>
                        <?= $form->field($model, 'scale_tickets')->checkbox() ?>
                        <?= $form->field($model, 'load_receipts')->checkbox() ?>
                        <?= $form->field($model, 'work_orders')->checkbox() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php $this->endBlock(); ?>
    <?php $activeTab = Yii::$app->request->get('tab', 'company'); ?>
    <?php echo Tabs::widget([
        'encodeLabels' => false,
        'items' => [
            [
                'label' => Yii::t('app', 'Company'),
                'content' => $this->blocks['company'],
                'active' => ($activeTab == 'company'),
            ],
            [
                'label' => Yii::t('app', 'Defaults'),
                'content' => $this->blocks['defaults'],
                'active' => ($activeTab == 'defaults')
            ],
            [
                'label' => Yii::t('app', 'Billing'),
                'content' => $this->blocks['billing'],
                'active' => ($activeTab == 'billing')
            ],
            [
                'label' => Yii::t('app', 'Contacts'),
                'content' => $this->blocks['contacts'],
                'active' => ($activeTab == 'contacts'),
                'disabled' => !isset($model->id),
            ],
        ]]); ?>
    <?php echo $form->errorSummary($model); ?>
    <?php echo Html::submitButton('<i class="fas fa fa-check"></i> ' . ($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')), ['id' => 'save-' . $model->formName(), 'class' => 'btn btn-success']); ?>
    <?php ActiveForm::end(); ?>
</section>