<?php
/**
 * /var/www/html/frontend/runtime/giiant/d4b4964a63cc95065fa0ae19074007ee
 *
 * @package default
 */


use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\bootstrap4\Tabs;

/**
 *
 * @var yii\web\View $this
 * @var common\models\Carrier $model
 */
$copyParams = $model->attributes;

$this->title = Yii::t('app', 'Carrier');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Carriers'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>
<div class="giiant-crud carrier-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?php echo \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?php echo Yii::t('app', 'Carrier') ?>
        <small>
            <?php echo Html::encode($model->name) ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='float-left'>
            <?php echo Html::a(
    '<i class="fa fa-edit"></i> ' . Yii::t('app', 'Edit'),
	['update', 'id' => $model->id],
	['class' => 'btn btn-sm btn-secondary']) ?>

            <?php echo Html::a(
    '<i class="fa fa-copy"></i> ' . Yii::t('app', 'Copy'),
	['create', 'id' => $model->id, 'Carrier'=>$copyParams],
	['class' => 'btn btn-sm btn-secondary']) ?>

            <?php echo Html::a(
    '<i class="fa fa-plus"></i> ' . Yii::t('app', 'New'),
	['create'],
	['class' => 'btn btn-sm btn-secondary']) ?>
        </div>

        <div class="float-right">
            <?php echo Html::a('<i class="fa fa-list"></i> '
            . Yii::t('app', 'Full list'), ['index'], ['class'=>'btn btn-sm btn-secondary']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('common\models\Carrier'); ?>


    <?php echo DetailView::widget([
		'model' => $model,
		'attributes' => [
			'notes:ntext',
			'special_instructions:ntext',
			'name',
			'address_1',
			'city',
			'zip',
			'main_phone',
			'disp_contact',
			'ar_contact',
			'account_no',
			'federal_id',
			'mail_list:boolean',
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'state_id',
				'value' => ($model->state ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['state/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->state->_label, ['state/view', 'id' => $model->state->id, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Carrier'=>['state_id' => $model->state_id]])
					:
					'<span class="label label-warning">?</span>'),
			],
			'address_2',
			'main_800',
			'main_fax',
			'email:email',
			'website',
			'other_contact',
		],
	]); ?>


    <hr/>

    <?php echo Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id],
	[
		'class' => 'btn btn-danger',
	    'data-confirm' => '' . Yii::t('app', 'Are you sure to delete this item?') . '',
		'data-method' => 'post',
	]); ?>
    <?php $this->endBlock(); ?>



    <?php echo Tabs::widget(
	[
		'id' => 'relation-tabs',
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => '<b class=""># '.Html::encode($model->id).'</b>',
				'content' => $this->blocks['common\models\Carrier'],
				'active'  => true,
			],
		]
	]
);
?>
</div>
