<?php

namespace common\models;

use Yii;
use \common\models\base\Account as BaseAccount;

/**
 * This is the model class for table "account".
 */
class Account extends BaseAccount
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->isNewRecord) {
            $this->active = true;
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'account' => Yii::t('app', 'Account No'),
            'description' => Yii::t('app', 'Description'),
            'account_type' => Yii::t('app', 'Type'),
            'filter' => Yii::t('app', 'Filter'),
            'active' => Yii::t('app', 'Active'),
            'hidden' => Yii::t('app', 'Hidden'),
        ];
    }

    public function get_label()
    {
        return $this->account . " (" . $this->accountType->type . " - " . $this->description . ")";
    }

    public static function getFilterByType($type, $returnQuery = false)
    {
        $f = function (\yii\db\Query $query) use ($type) {
            if ($query instanceof \yii\db\ActiveQuery) {
                $query->joinWith('accountType');
            } else {
                $query->innerJoin(AccountType::tableName(), sprintf('%s.account_type=%s.id', static::tableName(), AccountType::tableName()));
            }
            $query->where($type ? ['type' => $type, 'active' => true] : ['active' => true]);
        };
        if (!$returnQuery) {
            return $f;
        }
        $query = static::find();
        $f($query);
        return $query;
    }
}
