<?php
/**
 * /var/www/html/frontend/runtime/giiant/d4b4964a63cc95065fa0ae19074007ee
 *
 * @package default
 */


use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\bootstrap4\Tabs;

/**
 *
 * @var yii\web\View $this
 * @var common\models\Truck $model
 */
$copyParams = $model->attributes;

$this->title = Yii::t('app', 'Truck');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Trucks'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>
<div class="giiant-crud truck-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?php echo \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?php echo Yii::t('app', 'Truck') ?>
        <small>
            <?php echo Html::encode($model->id) ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='float-left'>
            <?php echo Html::a(
                '<i class="fa fa-edit"></i> ' . Yii::t('app', 'Edit'),
                ['update', 'id' => $model->id],
                ['class' => 'btn btn-sm btn-secondary']) ?>

            <?php echo Html::a(
                '<i class="fa fa-copy"></i> ' . Yii::t('app', 'Copy'),
                ['create', 'id' => $model->id, 'Truck' => $copyParams],
                ['class' => 'btn btn-sm btn-secondary']) ?>

            <?php echo Html::a(
                '<i class="fa fa-plus"></i> ' . Yii::t('app', 'New'),
                ['create'],
                ['class' => 'btn btn-sm btn-secondary']) ?>
        </div>

        <div class="float-right">
            <?php echo Html::a('<i class="fa fa-list"></i> '
                . Yii::t('app', 'Full list'), ['index'], ['class' => 'btn btn-sm btn-secondary']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('common\models\Truck'); ?>


    <?php echo DetailView::widget([
        'model' => $model,
        'attributes' => [
            'type',
            'year',
            'make',
            'model',
            'serial',
            'tare',
            'in_svc:date',
            'vin',
            'license',
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'license_state_id',
                'value' => ($model->licenseState ?
                    Html::a('<i class="glyphicon glyphicon-list"></i>', ['state/index']) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> ' . $model->licenseState->_label, ['state/view', 'id' => $model->licenseState->id,]) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Truck' => ['license_state_id' => $model->license_state_id]])
                    :
                    '<span class="label label-warning">?</span>'),
            ],
            'carb_id',
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'office_id',
                'value' => ($model->office ?
                    Html::a('<i class="glyphicon glyphicon-list"></i>', ['office/index']) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> ' . $model->office->_label, ['office/view', 'id' => $model->office->id,]) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Truck' => ['office_id' => $model->office_id]])
                    :
                    '<span class="label label-warning">?</span>'),
            ],
            'out_of_service',
            'status',
            'notes:ntext',
        ],
    ]); ?>


    <hr/>

    <?php echo Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id],
        [
            'class' => 'btn btn-danger',
            'data-confirm' => Yii::t('app', 'Are you sure to delete this item?'),
            'data-method' => 'post',
        ]); ?>
    <?php $this->endBlock(); ?>



    <?php $this->beginBlock('Type0'); ?>
    <div style='position: relative'>
        <div style='position:absolute; right: 0px; top: 0px;'>
            <?php echo Html::a(
                '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List All') . ' Type0',
                ['truck-type/index'],
                ['class' => 'btn text-muted btn-xs']
            ) ?>
            <?php echo Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New') . ' Type0',
                ['truck-type/create', 'TruckType' => ['type' => $model->id]],
                ['class' => 'btn btn-success btn-xs']
            ); ?>
        </div>
    </div>
    <?php Pjax::begin(['id' => 'pjax-Type0', 'enableReplaceState' => false, 'linkSelector' => '#pjax-Type0 ul.pagination a, th a']) ?>
    <?php echo
        '<div class="table-responsive">'
        . \yii\grid\GridView::widget([
            'layout' => '{summary}<div class="text-center">{pager}</div>{items}<div class="text-center">{pager}</div>',
            'dataProvider' => new \yii\data\ActiveDataProvider([
                'query' => $model->getType0(),
                'pagination' => [
                    'pageSize' => 20,
                    'pageParam' => 'page-type0',
                ]
            ]),
            'pager' => [
                'class' => yii\widgets\LinkPager::className(),
                'firstPageLabel' => 'First',
                'lastPageLabel' => 'Last'
            ],
            'columns' => [
                'description',
                'max_weight',
                'axles',
                'height',
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{view} {update}',
                    'contentOptions' => ['nowrap' => 'nowrap'],
                    'urlCreator' => function ($action, $model, $key, $index) {
                        // using the column name as key, not mapping to 'id' like the standard generator
                        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string)$key];
                        $params[0] = 'truck-type' . '/' . $action;
                        $params['TruckType'] = ['type' => $model->primaryKey()[0]];
                        return $params;
                    },
                    'buttons' => [

                    ],
                    'controller' => 'truck-type'
                ],
            ]
        ])
        . '</div>'
    ?>
    <?php Pjax::end() ?>
    <?php $this->endBlock() ?>


    <?php $this->beginBlock('TruckOdometers'); ?>
    <div style='position: relative'>
        <div style='position:absolute; right: 0px; top: 0px;'>
            <?php echo Html::a(
                '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('app', 'List All') . ' ' . Yii::t('app', 'Truck Odometers'),
                ['truck-odometer/index'],
                ['class' => 'btn text-muted btn-xs']
            ) ?>
            <?php echo Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'New') . ' ' . Yii::t('app', 'Truck Odometer'),
                ['truck-odometer/create', 'TruckOdometer' => ['truck_id' => $model->id]],
                ['class' => 'btn btn-success btn-xs']
            ); ?>
        </div>
    </div>
    <?php Pjax::begin(['id' => 'pjax-TruckOdometers', 'enableReplaceState' => false, 'linkSelector' => '#pjax-TruckOdometers ul.pagination a, th a']) ?>
    <?php echo
        '<div class="table-responsive">'
        . \yii\grid\GridView::widget([
            'layout' => '{summary}<div class="text-center">{pager}</div>{items}<div class="text-center">{pager}</div>',
            'dataProvider' => new \yii\data\ActiveDataProvider([
                'query' => $model->getTruckOdometers(),
                'pagination' => [
                    'pageSize' => 20,
                    'pageParam' => 'page-truckodometers',
                ]
            ]),
            'pager' => [
                'class' => yii\widgets\LinkPager::className(),
                'firstPageLabel' => 'First',
                'lastPageLabel' => 'Last'
            ],
            'columns' => [
                'id',
                'odometer',
                // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                [
                    'class' => yii\grid\DataColumn::className(),
                    'attribute' => 'updated_by',
                    'value' => function ($model) {
                        if ($rel = $model->updatedBy) {
                            return Html::a($rel->id, ['user/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                        } else {
                            return '';
                        }
                    },
                    'format' => 'raw',
                ],
                'updated_at',
                // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                [
                    'class' => yii\grid\DataColumn::className(),
                    'attribute' => 'created_by',
                    'value' => function ($model) {
                        if ($rel = $model->createdBy) {
                            return Html::a($rel->id, ['user/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                        } else {
                            return '';
                        }
                    },
                    'format' => 'raw',
                ],
                'created_at',
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{view} {update}',
                    'contentOptions' => ['nowrap' => 'nowrap'],
                    'urlCreator' => function ($action, $model, $key, $index) {
                        // using the column name as key, not mapping to 'id' like the standard generator
                        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string)$key];
                        $params[0] = 'truck-odometer' . '/' . $action;
                        $params['TruckOdometer'] = ['truck_id' => $model->primaryKey()[0]];
                        return $params;
                    },
                    'buttons' => [

                    ],
                    'controller' => 'truck-odometer'
                ],
            ]
        ])
        . '</div>'
    ?>
    <?php Pjax::end() ?>
    <?php $this->endBlock() ?>


    <?php echo Tabs::widget(
        [
            'id' => 'relation-tabs',
            'encodeLabels' => false,
            'items' => [
                [
                    'label' => '<b class=""># ' . Html::encode($model->id) . '</b>',
                    'content' => $this->blocks['common\models\Truck'],
                    'active' => true,
                ],
                [
                    'content' => $this->blocks['Type0'],
                    'label' => '<small>Type0 <span class="badge badge-default">' . $model->getType0()->count() . '</span></small>',
                    'active' => false,
                ],
                [
                    'content' => $this->blocks['TruckOdometers'],
                    'label' => '<small>Truck Odometers <span class="badge badge-default">' . $model->getTruckOdometers()->count() . '</span></small>',
                    'active' => false,
                ],
            ]
        ]
    );
    ?>
</div>
