<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\bootstrap4\Tabs;

/**
 * @var yii\web\View $this
 * @var common\models\Driver $model
 */
$copyParams = $model->attributes;

$this->title = Yii::t('app', 'Driver');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Drivers'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>
<div class="giiant-crud driver-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('app', 'Driver') ?>
        <small><?= Html::encode($model->id) ?></small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='float-left'>
            <?= Html::a('<i class="fa fa-edit"></i> ' . Yii::t('app', 'Edit'), ['update', 'id' => $model->id], ['class' => 'btn btn-sm btn-secondary']) ?>

            <?= Html::a('<i class="fa fa-copy"></i> ' . Yii::t('app', 'Copy'), ['create', 'id' => $model->id, 'Driver' => $copyParams], ['class' => 'btn btn-sm btn-secondary']) ?>

            <?= Html::a('<i class="fa fa-plus"></i> ' . Yii::t('app', 'New'), ['create'], ['class' => 'btn btn-sm btn-secondary']) ?>
        </div>

        <div class="float-right">
            <?= Html::a('<i class="fa fa-list"></i> ' . Yii::t('app', 'Full list'), ['index'], ['class' => 'btn btn-sm btn-secondary']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('common\models\Driver'); ?>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'last_name',
            'first_name',
            'middle_name',
            'address_1',
            'address_2',
            'city',
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'state_id',
                'value' => ($model->state ?
                    Html::a('<i class="glyphicon glyphicon-list"></i>', ['state/index']) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> ' . $model->state->_label, ['state/view', 'id' => $model->state->id,]) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Driver' => ['state_id' => $model->state_id]])
                    :
                    '<span class="label label-warning">?</span>'),
            ],
            'zip',
            'telephone',
            'cell_phone',
            'other_phone',
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'office_id',
                'value' => ($model->office ?
                    Html::a('<i class="glyphicon glyphicon-list"></i>', ['office/index']) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> ' . $model->office->_label, ['office/view', 'id' => $model->office->id,]) . ' ' .
                    Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Driver' => ['office_id' => $model->office_id]])
                    :
                    '<span class="label label-warning">?</span>'),
            ],
            'web_id',
            'email_address:email',
            'user_defined_1',
            'user_defined_2',
            'user_defined_3',
            'social_sec_no',
            'passport_no',
            'passport_exp',
            'date_of_birth',
            'hire_date',
            'mail_list:boolean',
            'maintenance:boolean',
            'notes:ntext',
            'status'
        ],
    ]); ?>


    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Delete'), ['delete', 'id' => $model->id],
        [
            'class' => 'btn btn-danger',
            'data-confirm' => '' . Yii::t('app', 'Are you sure to delete this item?') . '',
            'data-method' => 'post',
        ]); ?>
    <?php $this->endBlock(); ?>



    <?= Tabs::widget(
        [
            'id' => 'relation-tabs',
            'encodeLabels' => false,
            'items' => [
                [
                    'label' => '<b class=""># ' . Html::encode($model->id) . '</b>',
                    'content' => $this->blocks['common\models\Driver'],
                    'active' => true,
                ],
            ]
        ]
    );
    ?>
</div>
