<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "accessorial_pay".
 *
 * @property integer $id
 * @property integer $office_id
 * @property integer $accessorial_rating_id
 * @property string $rate_each
 * @property string $calc_by
 * @property string $basis
 * @property boolean $inactive
 *
 * @property \common\models\AccessorialRating $accessorialRating
 * @property \common\models\Office $office
 * @property string $aliasModel
 */
abstract class AccessorialPay extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'accessorial_pay';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['office_id', 'accessorial_rating_id'], 'required'],
            [['office_id', 'accessorial_rating_id'], 'default', 'value' => null],
            [['office_id', 'accessorial_rating_id'], 'integer'],
            [['rate_each'], 'number'],
            [['inactive'], 'boolean'],
            [['calc_by', 'basis'], 'string', 'max' => 255],
            [['office_id', 'accessorial_rating_id'], 'unique', 'targetAttribute' => ['office_id', 'accessorial_rating_id']],
            [['accessorial_rating_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\AccessorialRating::className(), 'targetAttribute' => ['accessorial_rating_id' => 'id']],
            [['office_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Office::className(), 'targetAttribute' => ['office_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'office_id' => Yii::t('app', 'Office ID'),
            'accessorial_rating_id' => Yii::t('app', 'Accessorial Rating ID'),
            'rate_each' => Yii::t('app', 'Rate Each'),
            'calc_by' => Yii::t('app', 'Calc By'),
            'basis' => Yii::t('app', 'Basis'),
            'inactive' => Yii::t('app', 'Inactive'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccessorialRating()
    {
        return $this->hasOne(\common\models\AccessorialRating::className(), ['id' => 'accessorial_rating_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffice()
    {
        return $this->hasOne(\common\models\Office::className(), ['id' => 'office_id']);
    }




}
