<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "account".
 *
 * @property string $account
 * @property string $description
 * @property integer $account_type
 * @property string $filter
 * @property boolean $active
 * @property boolean $hidden
 *
 * @property \common\models\AccountType $accountType
 * @property string $aliasModel
 */
abstract class Account extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'account';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['account', 'description', 'account_type', 'filter'], 'required'],
            [['account_type'], 'default', 'value' => null],
            [['account_type'], 'integer'],
            [['active', 'hidden'], 'boolean'],
            [['account'], 'string', 'max' => 4],
            [['description', 'filter'], 'string', 'max' => 255],
            [['account'], 'unique'],
            [['account_type'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\AccountType::className(), 'targetAttribute' => ['account_type' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'account' => Yii::t('app', 'Account'),
            'description' => Yii::t('app', 'Description'),
            'account_type' => Yii::t('app', 'Account Type'),
            'filter' => Yii::t('app', 'Filter'),
            'active' => Yii::t('app', 'Active'),
            'hidden' => Yii::t('app', 'Hidden'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccountType()
    {
        return $this->hasOne(\common\models\AccountType::className(), ['id' => 'account_type']);
    }




}
