<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "business_direction".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \common\models\Company[] $companies
 * @property \common\models\CompanyBusinessDirection[] $companyBusinessDirections
 * @property string $aliasModel
 */
abstract class BusinessDirection extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'business_direction';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompanies()
    {
        return $this->hasMany(\common\models\Company::className(), ['business_direction_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompanyBusinessDirections()
    {
        return $this->hasMany(\common\models\CompanyBusinessDirection::className(), ['business_direction_id' => 'id']);
    }




}
