<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "carrier_contact_note".
 *
 * @property integer $id
 * @property integer $carrier_id
 * @property string $contact
 * @property string $code
 * @property string $notes
 * @property string $next_contact
 * @property boolean $post_reminder
 * @property string $created_at
 *
 * @property \common\models\Carrier $carrier
 * @property \common\models\CompanyNoteCode $code0
 * @property string $aliasModel
 */
abstract class CarrierContactNote extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'carrier_contact_note';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['carrier_id', 'contact', 'post_reminder'], 'required'],
            [['carrier_id'], 'default', 'value' => null],
            [['carrier_id'], 'integer'],
            [['notes'], 'string'],
            [['next_contact'], 'safe'],
            [['post_reminder'], 'boolean'],
            [['contact', 'code'], 'string', 'max' => 255],
            [['carrier_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Carrier::className(), 'targetAttribute' => ['carrier_id' => 'id']],
            [['code'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\CompanyNoteCode::className(), 'targetAttribute' => ['code' => 'code']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'carrier_id' => Yii::t('app', 'Carrier ID'),
            'contact' => Yii::t('app', 'Contact'),
            'code' => Yii::t('app', 'Code'),
            'notes' => Yii::t('app', 'Notes'),
            'next_contact' => Yii::t('app', 'Next Contact'),
            'post_reminder' => Yii::t('app', 'Post Reminder'),
            'created_at' => Yii::t('app', 'Created At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarrier()
    {
        return $this->hasOne(\common\models\Carrier::className(), ['id' => 'carrier_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCode0()
    {
        return $this->hasOne(\common\models\CompanyNoteCode::className(), ['code' => 'code']);
    }




}
