<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "carrier_ranking".
 *
 * @property string $code
 * @property integer $order
 * @property string $description
 *
 * @property \common\models\CarrierProfile[] $carrierProfiles
 * @property string $aliasModel
 */
abstract class CarrierRanking extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'carrier_ranking';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code', 'order'], 'required'],
            [['order'], 'default', 'value' => null],
            [['order'], 'integer'],
            [['code', 'description'], 'string', 'max' => 255],
            [['code'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'code' => Yii::t('app', 'Code'),
            'order' => Yii::t('app', 'Order'),
            'description' => Yii::t('app', 'Description'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarrierProfiles()
    {
        return $this->hasMany(\common\models\CarrierProfile::className(), ['ranking' => 'code']);
    }




}
