<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "chat_message".
 *
 * @property integer $id
 * @property integer $reply_id
 * @property integer $load_id
 * @property string $message
 * @property integer $user_id
 * @property string $created_at
 * @property string $updated_at
 * @property integer $created_by
 *
 * @property \common\models\ChatMessage $reply
 * @property \common\models\ChatMessage[] $chatMessages
 * @property \common\models\Load $load
 * @property \common\models\User $createdBy
 * @property \common\models\User $user
 * @property \common\models\ChatMessageSeen[] $chatMessageSeens
 * @property \common\models\User[] $users
 * @property string $aliasModel
 */
abstract class ChatMessage extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'chat_message';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['reply_id', 'load_id', 'user_id'], 'default', 'value' => null],
            [['reply_id', 'load_id', 'user_id'], 'integer'],
            [['message'], 'required'],
            [['message'], 'string', 'max' => 4096],
            [['reply_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\ChatMessage::className(), 'targetAttribute' => ['reply_id' => 'id']],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['load_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'reply_id' => Yii::t('app', 'Reply ID'),
            'load_id' => Yii::t('app', 'Load ID'),
            'message' => Yii::t('app', 'Message'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'created_by' => Yii::t('app', 'Created By'),
            'user_id' => Yii::t('app', 'User ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReply()
    {
        return $this->hasOne(\common\models\ChatMessage::className(), ['id' => 'reply_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChatMessages()
    {
        return $this->hasMany(\common\models\ChatMessage::className(), ['reply_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'load_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChatMessageSeens()
    {
        return $this->hasMany(\common\models\ChatMessageSeen::className(), ['message_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(\common\models\User::className(), ['id' => 'user_id'])->viaTable('{{%chat_message_seen}}', ['message_id' => 'id']);
    }




}
