<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "commodity".
 *
 * @property integer $id
 * @property string $description
 * @property string $hazmat_code
 * @property string $class
 * @property string $type
 *
 * @property \common\models\Hazmat $hazmatCode
 * @property string $aliasModel
 */
abstract class Commodity extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'commodity';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description', 'hazmat_code', 'class', 'type'], 'string', 'max' => 255],
            [['hazmat_code'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Hazmat::className(), 'targetAttribute' => ['hazmat_code' => 'code']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app/model/field', 'ID'),
            'description' => Yii::t('app/model/field', 'Description'),
            'hazmat_code' => Yii::t('app/model/field', 'Hazmat Code'),
            'class' => Yii::t('app/model/field', 'Class'),
            'type' => Yii::t('app/model/field', 'Type'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHazmatCode()
    {
        return $this->hasOne(\common\models\Hazmat::className(), ['code' => 'hazmat_code']);
    }




}
