<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "company_business_direction".
 *
 * @property integer $id
 * @property integer $company_id
 * @property integer $business_direction_id
 *
 * @property \common\models\BusinessDirection $businessDirection
 * @property \common\models\Company $company
 * @property string $aliasModel
 */
abstract class CompanyBusinessDirection extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'company_business_direction';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['company_id', 'business_direction_id'], 'required'],
            [['company_id', 'business_direction_id'], 'default', 'value' => null],
            [['company_id', 'business_direction_id'], 'integer'],
            [['company_id', 'business_direction_id'], 'unique', 'targetAttribute' => ['company_id', 'business_direction_id']],
            [['business_direction_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\BusinessDirection::className(), 'targetAttribute' => ['business_direction_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'company_id' => Yii::t('app', 'Company ID'),
            'business_direction_id' => Yii::t('app', 'Business Direction ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBusinessDirection()
    {
        return $this->hasOne(\common\models\BusinessDirection::className(), ['id' => 'business_direction_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\common\models\Company::className(), ['id' => 'company_id']);
    }




}
