<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "company_note_code".
 *
 * @property string $code
 * @property string $description
 *
 * @property \common\models\CarrierContactNote[] $carrierContactNotes
 * @property \common\models\CustomerContactNote[] $customerContactNotes
 * @property \common\models\VendorContactNote[] $vendorContactNotes
 * @property string $aliasModel
 */
abstract class CompanyNoteCode extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'company_note_code';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code'], 'required'],
            [['code', 'description'], 'string', 'max' => 255],
            [['code'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'code' => Yii::t('app', 'Code'),
            'description' => Yii::t('app', 'Description'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarrierContactNotes()
    {
        return $this->hasMany(\common\models\CarrierContactNote::className(), ['code' => 'code']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomerContactNotes()
    {
        return $this->hasMany(\common\models\CustomerContactNote::className(), ['code' => 'code']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendorContactNotes()
    {
        return $this->hasMany(\common\models\VendorContactNote::className(), ['code' => 'code']);
    }




}
