<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "cron".
 *
 * @property integer $id
 * @property string $task
 * @property string $data
 * @property string $start_time
 * @property integer $max_retry_count
 * @property integer $attempts
 * @property integer $next_attempt_interval
 * @property string $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class Cron extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cron';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['task', 'start_time', 'max_retry_count', 'next_attempt_interval'], 'required'],
            [['data'], 'string'],
            [['start_time'], 'safe'],
            [['max_retry_count', 'attempts', 'next_attempt_interval'], 'default', 'value' => null],
            [['max_retry_count', 'attempts', 'next_attempt_interval'], 'integer'],
            [['task', 'status'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'task' => Yii::t('app', 'Task'),
            'data' => Yii::t('app', 'Data'),
            'start_time' => Yii::t('app', 'Start Time'),
            'max_retry_count' => Yii::t('app', 'Max Retry Count'),
            'attempts' => Yii::t('app', 'Attempts'),
            'next_attempt_interval' => Yii::t('app', 'Next Attempt Interval'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }




}
