<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "customer_contact_note".
 *
 * @property integer $id
 * @property integer $customer_id
 * @property string $contact
 * @property string $code
 * @property string $notes
 * @property string $next_contact
 * @property boolean $post_reminder
 * @property string $created_at
 *
 * @property \common\models\CompanyNoteCode $code0
 * @property \common\models\Customer $customer
 * @property string $aliasModel
 */
abstract class CustomerContactNote extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'customer_contact_note';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['customer_id', 'contact', 'post_reminder'], 'required'],
            [['customer_id'], 'default', 'value' => null],
            [['customer_id'], 'integer'],
            [['notes'], 'string'],
            [['next_contact'], 'safe'],
            [['post_reminder'], 'boolean'],
            [['contact', 'code'], 'string', 'max' => 255],
            [['code'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\CompanyNoteCode::className(), 'targetAttribute' => ['code' => 'code']],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Customer::className(), 'targetAttribute' => ['customer_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'customer_id' => Yii::t('app', 'Customer ID'),
            'contact' => Yii::t('app', 'Contact'),
            'code' => Yii::t('app', 'Code'),
            'notes' => Yii::t('app', 'Notes'),
            'next_contact' => Yii::t('app', 'Next Contact'),
            'post_reminder' => Yii::t('app', 'Post Reminder'),
            'created_at' => Yii::t('app', 'Created At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCode0()
    {
        return $this->hasOne(\common\models\CompanyNoteCode::className(), ['code' => 'code']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(\common\models\Customer::className(), ['id' => 'customer_id']);
    }




}
