<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "driver_adjustment".
 *
 * @property integer $id
 * @property integer $driver_id
 * @property string $payroll_adjustment_code
 * @property integer $post_to_carrier_id
 * @property integer $post_to_driver_id
 * @property integer $post_to_vendor_id
 * @property string $account
 * @property string $calc_by
 * @property string $amount
 * @property integer $cap_id
 * @property integer $truck_id
 * @property string $created_at
 * @property string $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \common\models\Account $account0
 * @property \common\models\Cap $cap
 * @property \common\models\Carrier $postToCarrier
 * @property \common\models\Driver $driver
 * @property \common\models\Driver $postToDriver
 * @property \common\models\PayrollAdjustmentCode $payrollAdjustmentCode
 * @property \common\models\Truck $truck
 * @property \common\models\User $createdBy
 * @property \common\models\User $updatedBy
 * @property \common\models\Vendor $postToVendor
 * @property string $aliasModel
 */
abstract class DriverAdjustment extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'driver_adjustment';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['driver_id'], 'required'],
            [['driver_id', 'post_to_carrier_id', 'post_to_driver_id', 'post_to_vendor_id', 'cap_id', 'truck_id'], 'default', 'value' => null],
            [['driver_id', 'post_to_carrier_id', 'post_to_driver_id', 'post_to_vendor_id', 'cap_id', 'truck_id'], 'integer'],
            [['amount'], 'number'],
            [['payroll_adjustment_code', 'account', 'calc_by'], 'string', 'max' => 255],
            [['account'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Account::className(), 'targetAttribute' => ['account' => 'account']],
            [['cap_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Cap::className(), 'targetAttribute' => ['cap_id' => 'id']],
            [['post_to_carrier_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Carrier::className(), 'targetAttribute' => ['post_to_carrier_id' => 'id']],
            [['driver_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Driver::className(), 'targetAttribute' => ['driver_id' => 'id']],
            [['post_to_driver_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Driver::className(), 'targetAttribute' => ['post_to_driver_id' => 'id']],
            [['payroll_adjustment_code'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\PayrollAdjustmentCode::className(), 'targetAttribute' => ['payroll_adjustment_code' => 'code']],
            [['truck_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Truck::className(), 'targetAttribute' => ['truck_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['updated_by' => 'id']],
            [['post_to_vendor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Vendor::className(), 'targetAttribute' => ['post_to_vendor_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'driver_id' => Yii::t('app', 'Driver ID'),
            'payroll_adjustment_code' => Yii::t('app', 'Payroll Adjustment Code'),
            'post_to_carrier_id' => Yii::t('app', 'Post To Carrier ID'),
            'post_to_driver_id' => Yii::t('app', 'Post To Driver ID'),
            'post_to_vendor_id' => Yii::t('app', 'Post To Vendor ID'),
            'account' => Yii::t('app', 'Account'),
            'calc_by' => Yii::t('app', 'Calc By'),
            'amount' => Yii::t('app', 'Amount'),
            'cap_id' => Yii::t('app', 'Cap ID'),
            'truck_id' => Yii::t('app', 'Truck ID'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_by' => Yii::t('app', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccount0()
    {
        return $this->hasOne(\common\models\Account::className(), ['account' => 'account']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCap()
    {
        return $this->hasOne(\common\models\Cap::className(), ['id' => 'cap_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPostToCarrier()
    {
        return $this->hasOne(\common\models\Carrier::className(), ['id' => 'post_to_carrier_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDriver()
    {
        return $this->hasOne(\common\models\Driver::className(), ['id' => 'driver_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPostToDriver()
    {
        return $this->hasOne(\common\models\Driver::className(), ['id' => 'post_to_driver_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayrollAdjustmentCode()
    {
        return $this->hasOne(\common\models\PayrollAdjustmentCode::className(), ['code' => 'payroll_adjustment_code']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTruck()
    {
        return $this->hasOne(\common\models\Truck::className(), ['id' => 'truck_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'updated_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPostToVendor()
    {
        return $this->hasOne(\common\models\Vendor::className(), ['id' => 'post_to_vendor_id']);
    }




}
