<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "fuelcard_account_config".
 *
 * @property string $type
 * @property array $config
 * @property string $aliasModel
 */
abstract class FuelcardAccountConfig extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'fuelcard_account_config';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'config'], 'required'],
            [['config'], 'safe'],
            [['type'], 'string', 'max' => 255],
            [['type'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'type' => Yii::t('app', 'Type'),
            'config' => Yii::t('app', 'Config'),
        ];
    }




}
