<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "fuel_product_codes".
 *
 * @property integer $id
 * @property string $provider
 * @property string $description
 * @property string $oo_acct
 * @property string $cd_acct
 * @property string $fee_amt
 * @property string $fee_acct
 *
 * @property \common\models\Account $ooAcct
 * @property \common\models\Account $cdAcct
 * @property \common\models\Account $feeAcct
 * @property string $aliasModel
 */
abstract class FuelProductCode extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'fuel_product_codes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['provider'], 'required'],
            [['fee_amt'], 'number'],
            [['provider'], 'string', 'max' => 32],
            [['description'], 'string', 'max' => 64],
            [['oo_acct', 'cd_acct', 'fee_acct'], 'string', 'max' => 4],
            [['provider', 'description'], 'unique', 'targetAttribute' => ['provider', 'description']],
            [['oo_acct'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Account::className(), 'targetAttribute' => ['oo_acct' => 'account']],
            [['cd_acct'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Account::className(), 'targetAttribute' => ['cd_acct' => 'account']],
            [['fee_acct'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Account::className(), 'targetAttribute' => ['fee_acct' => 'account']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'provider' => Yii::t('app', 'Provider'),
            'description' => Yii::t('app', 'Description'),
            'oo_acct' => Yii::t('app', 'Oo Acct'),
            'cd_acct' => Yii::t('app', 'Cd Acct'),
            'fee_amt' => Yii::t('app', 'Fee Amt'),
            'fee_acct' => Yii::t('app', 'Fee Acct'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'oo_acct' => Yii::t('app', 'Owner Operator Account'),
            'cd_acct' => Yii::t('app', 'Company Driver Account'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOoAcct()
    {
        return $this->hasOne(\common\models\Account::className(), ['account' => 'oo_acct']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCdAcct()
    {
        return $this->hasOne(\common\models\Account::className(), ['account' => 'cd_acct']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFeeAcct()
    {
        return $this->hasOne(\common\models\Account::className(), ['account' => 'fee_acct']);
    }




}
