<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "load_rating_zipzip".
 *
 * @property integer $id
 * @property string $matrix
 * @property string $zip_1_start
 * @property string $zip_1_end
 * @property string $zip_2_start
 * @property string $zip_2_end
 * @property integer $low_wgt
 * @property integer $high_wgt
 * @property integer $bill_miles
 * @property string $rate
 * @property string $base_rate
 * @property integer $base_miles
 * @property string $min
 * @property string $trl_type
 * @property string $pieces
 * @property string $description
 * @property integer $created_at
 *
 * @property \common\models\LoadRatingMatrix $matrix0
 * @property \common\models\TrailerType $trlType
 * @property string $aliasModel
 */
abstract class LoadRatingZipZip extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_rating_zipzip';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['matrix', 'zip_1_start', 'zip_1_end', 'zip_2_start', 'zip_2_end'], 'required'],
            [['low_wgt', 'high_wgt', 'bill_miles', 'base_miles'], 'default', 'value' => null],
            [['low_wgt', 'high_wgt', 'bill_miles', 'base_miles'], 'integer'],
            [['rate', 'base_rate', 'min', 'pieces'], 'number'],
            [['matrix'], 'string', 'max' => 5],
            [['zip_1_start', 'zip_1_end', 'zip_2_start', 'zip_2_end'], 'string', 'max' => 12],
            [['trl_type', 'description'], 'string', 'max' => 255],
            [['matrix'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\LoadRatingMatrix::className(), 'targetAttribute' => ['matrix' => 'number']],
            [['trl_type'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\TrailerType::className(), 'targetAttribute' => ['trl_type' => 'type']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'matrix' => Yii::t('app', 'Matrix'),
            'zip_1_start' => Yii::t('app', 'Zip 1 Start'),
            'zip_1_end' => Yii::t('app', 'Zip 1 End'),
            'zip_2_start' => Yii::t('app', 'Zip 2 Start'),
            'zip_2_end' => Yii::t('app', 'Zip 2 End'),
            'low_wgt' => Yii::t('app', 'Low Wgt'),
            'high_wgt' => Yii::t('app', 'High Wgt'),
            'bill_miles' => Yii::t('app', 'Bill Miles'),
            'rate' => Yii::t('app', 'Rate'),
            'base_rate' => Yii::t('app', 'Base Rate'),
            'base_miles' => Yii::t('app', 'Base Miles'),
            'min' => Yii::t('app', 'Min'),
            'trl_type' => Yii::t('app', 'Trl Type'),
            'pieces' => Yii::t('app', 'Pieces'),
            'description' => Yii::t('app', 'Description'),
            'created_at' => Yii::t('app', 'Created At'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'low_wgt' => Yii::t('app', 'CWT'),
            'high_wgt' => Yii::t('app', 'CWT'),
            'bill_miles' => Yii::t('app', 'FLAT,MILES'),
            'rate' => Yii::t('app', 'CWT,FLAT,MILES,POUND,PIECE,SPACE,TON,MULTI'),
            'base_rate' => Yii::t('app', 'MILES'),
            'base_miles' => Yii::t('app', 'MILES'),
            'min' => Yii::t('app', 'MILES,POUND'),
            'trl_type' => Yii::t('app', 'MILES'),
            'pieces' => Yii::t('app', 'LOT'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMatrix0()
    {
        return $this->hasOne(\common\models\LoadRatingMatrix::className(), ['number' => 'matrix']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrlType()
    {
        return $this->hasOne(\common\models\TrailerType::className(), ['type' => 'trl_type']);
    }




}
