<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "load_note".
 *
 * @property integer $id
 * @property integer $load_id
 * @property integer $last_action
 * @property string $notes
 * @property integer $created_by
 * @property string $created_at
 *
 * @property \common\models\Load $load
 * @property \common\models\LoadNoteType $lastAction
 * @property \common\models\User $createdBy
 * @property string $aliasModel
 */
abstract class LoadNote extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_note';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_id', 'notes'], 'required'],
            [['load_id', 'last_action'], 'default', 'value' => null],
            [['load_id', 'last_action'], 'integer'],
            [['notes'], 'string'],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['load_id' => 'id']],
            [['last_action'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\LoadNoteType::className(), 'targetAttribute' => ['last_action' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['created_by' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'load_id' => Yii::t('app', 'Load ID'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_at' => Yii::t('app', 'Created At'),
            'last_action' => Yii::t('app', 'Last Action'),
            'notes' => Yii::t('app', 'Notes'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'load_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLastAction()
    {
        return $this->hasOne(\common\models\LoadNoteType::className(), ['id' => 'last_action']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'created_by']);
    }




}
