<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "load_stop".
 *
 * @property integer $id
 * @property integer $load_id
 * @property integer $stop_number
 * @property string $stop_type
 * @property string $available_from
 * @property string $available_thru
 * @property string $time_from
 * @property string $time_to
 * @property integer $company_id
 * @property string $address
 * @property string $city
 * @property integer $state_id
 * @property string $zip
 * @property string $zone
 * @property string $phone
 * @property string $contact
 * @property string $reference
 * @property boolean $appt_required
 * @property string $appt_reference
 * @property string $notes
 * @property string $directions
 * @property string $arrived_date
 * @property string $arrived_time_in
 * @property string $arrived_time_out
 * @property integer $miles_to_next
 * @property string $status
 * @property double $lat
 * @property double $lon
 * @property string $company_name
 * @property integer $updated_by
 * @property string $updated_at
 * @property integer $created_by
 * @property string $created_at
 *
 * @property \common\models\LoadMovement $loadMovement
 * @property \common\models\Load $load
 * @property \common\models\Location $company
 * @property \common\models\State $state
 * @property \common\models\User $updatedBy
 * @property \common\models\User $createdBy
 * @property \common\models\Zone $zone0
 * @property string $aliasModel
 */
abstract class LoadStop extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_stop';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_id', 'stop_number', 'appt_required'], 'required'],
            [['load_id', 'stop_number', 'company_id', 'state_id', 'miles_to_next'], 'default', 'value' => null],
            [['load_id', 'stop_number', 'company_id', 'state_id', 'miles_to_next'], 'integer'],
            [['available_from', 'available_thru', 'time_from', 'time_to', 'arrived_date', 'arrived_time_in', 'arrived_time_out'], 'safe'],
            [['appt_required'], 'boolean'],
            [['notes', 'directions'], 'string'],
            [['lat', 'lon'], 'number'],
            [['stop_type', 'address', 'city', 'zone', 'phone', 'contact', 'reference', 'appt_reference', 'status', 'company_name'], 'string', 'max' => 255],
            [['zip'], 'string', 'max' => 10],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['load_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Location::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\State::className(), 'targetAttribute' => ['state_id' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['updated_by' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['zone'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Zone::className(), 'targetAttribute' => ['zone' => 'code']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'load_id' => Yii::t('app', 'Load ID'),
            'stop_number' => Yii::t('app', 'Stop Number'),
            'stop_type' => Yii::t('app', 'Stop Type'),
            'available_from' => Yii::t('app', 'Available From'),
            'available_thru' => Yii::t('app', 'Available Thru'),
            'time_from' => Yii::t('app', 'Time From'),
            'time_to' => Yii::t('app', 'Time To'),
            'company_id' => Yii::t('app', 'Company ID'),
            'address' => Yii::t('app', 'Address'),
            'city' => Yii::t('app', 'City'),
            'state_id' => Yii::t('app', 'State ID'),
            'zip' => Yii::t('app', 'Zip'),
            'zone' => Yii::t('app', 'Zone'),
            'phone' => Yii::t('app', 'Phone'),
            'contact' => Yii::t('app', 'Contact'),
            'reference' => Yii::t('app', 'Reference'),
            'appt_required' => Yii::t('app', 'Appt Required'),
            'appt_reference' => Yii::t('app', 'Appt Reference'),
            'notes' => Yii::t('app', 'Notes'),
            'directions' => Yii::t('app', 'Directions'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_at' => Yii::t('app', 'Created At'),
            'arrived_date' => Yii::t('app', 'Arrived Date'),
            'arrived_time_in' => Yii::t('app', 'Arrived Time In'),
            'arrived_time_out' => Yii::t('app', 'Arrived Time Out'),
            'miles_to_next' => Yii::t('app', 'Miles To Next'),
            'status' => Yii::t('app', 'Status'),
            'lat' => Yii::t('app', 'Lat'),
            'lon' => Yii::t('app', 'Lon'),
            'company_name' => Yii::t('app', 'Company Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadMovement()
    {
        return $this->hasOne(\common\models\LoadMovement::className(), ['load_stop_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'load_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\common\models\Location::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(\common\models\State::className(), ['id' => 'state_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'updated_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getZone0()
    {
        return $this->hasOne(\common\models\Zone::className(), ['code' => 'zone']);
    }




}
