<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "load_drop".
 *
 * @property integer $id
 * @property integer $load_id
 * @property integer $location_id
 * @property integer $drop_truck_id
 * @property integer $drop_trailer_id
 * @property integer $drop_trailer_2_id
 * @property integer $drop_driver_id
 * @property integer $drop_codriver_id
 * @property integer $drop_unit_id
 * @property string $drop_date
 * @property string $drop_time_from
 * @property string $drop_time_to
 * @property string $retrieve_date
 * @property string $retrieve_time
 * @property string $trailer_disposition
 * @property integer $retrieve_truck_id
 * @property integer $retrieve_trailer_id
 * @property integer $retrieve_trailer_2_id
 * @property integer $retrieve_driver_id
 * @property integer $retrieve_codriver_id
 * @property integer $retrieve_unit_id
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 *
 * @property \common\models\Driver $dropDriver
 * @property \common\models\Driver $dropCodriver
 * @property \common\models\Driver $retrieveDriver
 * @property \common\models\Driver $retrieveCodriver
 * @property \common\models\Load $load
 * @property \common\models\Location $location
 * @property \common\models\Trailer $dropTrailer
 * @property \common\models\Trailer $dropTrailer2
 * @property \common\models\Trailer $retrieveTrailer
 * @property \common\models\Trailer $retrieveTrailer2
 * @property \common\models\Truck $dropTruck
 * @property \common\models\Truck $retrieveTruck
 * @property \common\models\Unit $dropUnit
 * @property \common\models\Unit $retrieveUnit
 * @property \common\models\User $createdBy
 * @property \common\models\User $updatedBy
 * @property string $aliasModel
 */
abstract class LoadDrop extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_drop';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_id', 'location_id', 'drop_truck_id', 'drop_driver_id', 'drop_unit_id', 'drop_date', 'drop_time_from', 'trailer_disposition'], 'required'],
            [['load_id', 'location_id', 'drop_truck_id', 'drop_trailer_id', 'drop_trailer_2_id', 'drop_driver_id', 'drop_codriver_id', 'drop_unit_id', 'retrieve_truck_id', 'retrieve_trailer_id', 'retrieve_trailer_2_id', 'retrieve_driver_id', 'retrieve_codriver_id', 'retrieve_unit_id'], 'default', 'value' => null],
            [['load_id', 'location_id', 'drop_truck_id', 'drop_trailer_id', 'drop_trailer_2_id', 'drop_driver_id', 'drop_codriver_id', 'drop_unit_id', 'retrieve_truck_id', 'retrieve_trailer_id', 'retrieve_trailer_2_id', 'retrieve_driver_id', 'retrieve_codriver_id', 'retrieve_unit_id'], 'integer'],
            [['drop_date', 'drop_time_from', 'drop_time_to', 'retrieve_date', 'retrieve_time'], 'safe'],
            [['trailer_disposition'], 'string', 'max' => 255],
            [['drop_driver_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Driver::className(), 'targetAttribute' => ['drop_driver_id' => 'id']],
            [['drop_codriver_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Driver::className(), 'targetAttribute' => ['drop_codriver_id' => 'id']],
            [['retrieve_driver_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Driver::className(), 'targetAttribute' => ['retrieve_driver_id' => 'id']],
            [['retrieve_codriver_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Driver::className(), 'targetAttribute' => ['retrieve_codriver_id' => 'id']],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['load_id' => 'id']],
            [['location_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Location::className(), 'targetAttribute' => ['location_id' => 'id']],
            [['drop_trailer_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Trailer::className(), 'targetAttribute' => ['drop_trailer_id' => 'id']],
            [['drop_trailer_2_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Trailer::className(), 'targetAttribute' => ['drop_trailer_2_id' => 'id']],
            [['retrieve_trailer_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Trailer::className(), 'targetAttribute' => ['retrieve_trailer_id' => 'id']],
            [['retrieve_trailer_2_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Trailer::className(), 'targetAttribute' => ['retrieve_trailer_2_id' => 'id']],
            [['drop_truck_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Truck::className(), 'targetAttribute' => ['drop_truck_id' => 'id']],
            [['retrieve_truck_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Truck::className(), 'targetAttribute' => ['retrieve_truck_id' => 'id']],
            [['drop_unit_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Unit::className(), 'targetAttribute' => ['drop_unit_id' => 'id']],
            [['retrieve_unit_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Unit::className(), 'targetAttribute' => ['retrieve_unit_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['updated_by' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'load_id' => Yii::t('app', 'Load ID'),
            'location_id' => Yii::t('app', 'Location ID'),
            'drop_truck_id' => Yii::t('app', 'Drop Truck ID'),
            'drop_trailer_id' => Yii::t('app', 'Drop Trailer ID'),
            'drop_trailer_2_id' => Yii::t('app', 'Drop Trailer 2 ID'),
            'drop_driver_id' => Yii::t('app', 'Drop Driver ID'),
            'drop_codriver_id' => Yii::t('app', 'Drop Codriver ID'),
            'drop_unit_id' => Yii::t('app', 'Drop Unit ID'),
            'drop_date' => Yii::t('app', 'Drop Date'),
            'drop_time_from' => Yii::t('app', 'Drop Time From'),
            'drop_time_to' => Yii::t('app', 'Drop Time To'),
            'retrieve_date' => Yii::t('app', 'Retrieve Date'),
            'retrieve_time' => Yii::t('app', 'Retrieve Time'),
            'trailer_disposition' => Yii::t('app', 'Trailer Disposition'),
            'retrieve_truck_id' => Yii::t('app', 'Retrieve Truck ID'),
            'retrieve_trailer_id' => Yii::t('app', 'Retrieve Trailer ID'),
            'retrieve_trailer_2_id' => Yii::t('app', 'Retrieve Trailer 2 ID'),
            'retrieve_driver_id' => Yii::t('app', 'Retrieve Driver ID'),
            'retrieve_codriver_id' => Yii::t('app', 'Retrieve Codriver ID'),
            'retrieve_unit_id' => Yii::t('app', 'Retrieve Unit ID'),
            'created_at' => Yii::t('app', 'Created At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'updated_by' => Yii::t('app', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDropDriver()
    {
        return $this->hasOne(\common\models\Driver::className(), ['id' => 'drop_driver_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDropCodriver()
    {
        return $this->hasOne(\common\models\Driver::className(), ['id' => 'drop_codriver_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRetrieveDriver()
    {
        return $this->hasOne(\common\models\Driver::className(), ['id' => 'retrieve_driver_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRetrieveCodriver()
    {
        return $this->hasOne(\common\models\Driver::className(), ['id' => 'retrieve_codriver_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'load_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocation()
    {
        return $this->hasOne(\common\models\Location::className(), ['id' => 'location_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDropTrailer()
    {
        return $this->hasOne(\common\models\Trailer::className(), ['id' => 'drop_trailer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDropTrailer2()
    {
        return $this->hasOne(\common\models\Trailer::className(), ['id' => 'drop_trailer_2_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRetrieveTrailer()
    {
        return $this->hasOne(\common\models\Trailer::className(), ['id' => 'retrieve_trailer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRetrieveTrailer2()
    {
        return $this->hasOne(\common\models\Trailer::className(), ['id' => 'retrieve_trailer_2_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDropTruck()
    {
        return $this->hasOne(\common\models\Truck::className(), ['id' => 'drop_truck_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRetrieveTruck()
    {
        return $this->hasOne(\common\models\Truck::className(), ['id' => 'retrieve_truck_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDropUnit()
    {
        return $this->hasOne(\common\models\Unit::className(), ['id' => 'drop_unit_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRetrieveUnit()
    {
        return $this->hasOne(\common\models\Unit::className(), ['id' => 'retrieve_unit_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'updated_by']);
    }




}
