<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "load_movement".
 *
 * @property integer $id
 * @property string $action
 * @property integer $unit_id
 * @property integer $load_id
 * @property integer $load_stop_id
 * @property string $seal_no
 * @property integer $commodity_weight
 * @property string $commodity_pieces
 * @property string $bol
 * @property string $arrived_date
 * @property string $arrived_time_in
 * @property string $arrived_time_out
 * @property integer $location_id
 * @property integer $truck_id
 * @property integer $trailer_id
 * @property integer $driver_id
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 *
 * @property \common\models\Driver $driver
 * @property \common\models\Load $load
 * @property \common\models\LoadStop $loadStop
 * @property \common\models\Location $location
 * @property \common\models\Trailer $trailer
 * @property \common\models\Truck $truck
 * @property \common\models\Unit $unit
 * @property \common\models\User $createdBy
 * @property \common\models\User $updatedBy
 * @property string $aliasModel
 */
abstract class LoadMovement extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_movement';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['action', 'unit_id', 'load_id'], 'required'],
            [['unit_id', 'load_id', 'load_stop_id', 'commodity_weight', 'location_id', 'truck_id', 'trailer_id', 'driver_id'], 'default', 'value' => null],
            [['unit_id', 'load_id', 'load_stop_id', 'commodity_weight', 'location_id', 'truck_id', 'trailer_id', 'driver_id'], 'integer'],
            [['commodity_pieces'], 'number'],
            [['arrived_date', 'arrived_time_in', 'arrived_time_out'], 'safe'],
            [['action', 'seal_no', 'bol'], 'string', 'max' => 255],
            [['load_stop_id'], 'unique'],
            [['driver_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Driver::className(), 'targetAttribute' => ['driver_id' => 'id']],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['load_id' => 'id']],
            [['load_stop_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\LoadStop::className(), 'targetAttribute' => ['load_stop_id' => 'id']],
            [['location_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Location::className(), 'targetAttribute' => ['location_id' => 'id']],
            [['trailer_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Trailer::className(), 'targetAttribute' => ['trailer_id' => 'id']],
            [['truck_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Truck::className(), 'targetAttribute' => ['truck_id' => 'id']],
            [['unit_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Unit::className(), 'targetAttribute' => ['unit_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['updated_by' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'action' => Yii::t('app', 'Action'),
            'unit_id' => Yii::t('app', 'Unit ID'),
            'load_id' => Yii::t('app', 'Load ID'),
            'load_stop_id' => Yii::t('app', 'Load Stop ID'),
            'seal_no' => Yii::t('app', 'Seal No'),
            'commodity_weight' => Yii::t('app', 'Commodity Weight'),
            'commodity_pieces' => Yii::t('app', 'Commodity Pieces'),
            'bol' => Yii::t('app', 'Bol'),
            'arrived_date' => Yii::t('app', 'Arrived Date'),
            'arrived_time_in' => Yii::t('app', 'Arrived Time In'),
            'arrived_time_out' => Yii::t('app', 'Arrived Time Out'),
            'created_at' => Yii::t('app', 'Created At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'location_id' => Yii::t('app', 'Location ID'),
            'truck_id' => Yii::t('app', 'Truck ID'),
            'trailer_id' => Yii::t('app', 'Trailer ID'),
            'driver_id' => Yii::t('app', 'Driver ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDriver()
    {
        return $this->hasOne(\common\models\Driver::className(), ['id' => 'driver_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'load_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadStop()
    {
        return $this->hasOne(\common\models\LoadStop::className(), ['id' => 'load_stop_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocation()
    {
        return $this->hasOne(\common\models\Location::className(), ['id' => 'location_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrailer()
    {
        return $this->hasOne(\common\models\Trailer::className(), ['id' => 'trailer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTruck()
    {
        return $this->hasOne(\common\models\Truck::className(), ['id' => 'truck_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUnit()
    {
        return $this->hasOne(\common\models\Unit::className(), ['id' => 'unit_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'updated_by']);
    }




}
