<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "load_accessories".
 *
 * @property integer $id
 * @property integer $load_id
 * @property integer $matrix_id
 * @property integer $accessorial_id
 * @property string $reference
 * @property string $rate_each
 * @property string $units
 * @property string $amount
 * @property string $notes
 *
 * @property \common\models\AccessorialMatrix $matrix
 * @property \common\models\AccessorialPay $accessorial
 * @property \common\models\Load $load
 * @property string $aliasModel
 */
abstract class LoadAccessories extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_accessories';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_id', 'matrix_id', 'accessorial_id'], 'required'],
            [['load_id', 'matrix_id', 'accessorial_id'], 'default', 'value' => null],
            [['load_id', 'matrix_id', 'accessorial_id'], 'integer'],
            [['rate_each', 'units', 'amount'], 'number'],
            [['notes'], 'string'],
            [['reference'], 'string', 'max' => 32],
            [['matrix_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\AccessorialMatrix::className(), 'targetAttribute' => ['matrix_id' => 'id']],
            [['accessorial_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\AccessorialPay::className(), 'targetAttribute' => ['accessorial_id' => 'id']],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['load_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'load_id' => Yii::t('app', 'Load ID'),
            'matrix_id' => Yii::t('app', 'Matrix ID'),
            'accessorial_id' => Yii::t('app', 'Accessorial ID'),
            'reference' => Yii::t('app', 'Reference'),
            'rate_each' => Yii::t('app', 'Rate Each'),
            'units' => Yii::t('app', 'Units'),
            'amount' => Yii::t('app', 'Amount'),
            'notes' => Yii::t('app', 'Notes'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMatrix()
    {
        return $this->hasOne(\common\models\AccessorialMatrix::className(), ['id' => 'matrix_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccessorial()
    {
        return $this->hasOne(\common\models\AccessorialPay::className(), ['id' => 'accessorial_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'load_id']);
    }




}
