<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "location".
 *
 * @property integer $id
 * @property string $company_name
 * @property string $location_name
 * @property string $address
 * @property string $city
 * @property integer $state_id
 * @property string $zip
 * @property string $main_phone
 * @property string $main_800
 * @property string $main_fax
 * @property integer $office_id
 * @property string $contact
 * @property string $website
 * @property string $notes
 * @property boolean $appointment_required
 * @property boolean $trailer_pool_location
 * @property double $lat
 * @property double $lon
 * @property string $emergency
 * @property string $business_hours
 * @property string $zone
 * @property integer $bill_to
 * @property string $directions
 * @property string $location
 * @property string $marked_as_down
 * @property string $time_zone
 *
 * @property \common\models\Document[] $documents
 * @property \common\models\LoadStop[] $loadStops
 * @property \common\models\Customer $billTo
 * @property \common\models\Office $office
 * @property \common\models\State $state
 * @property \common\models\Zone $zone0
 * @property \common\models\LocationContact[] $locationContacts
 * @property \common\models\TrackingLog[] $trackingLogs
 * @property \common\models\Truck[] $trucks
 * @property string $aliasModel
 */
abstract class Location extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'location';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['company_name', 'address', 'city', 'zip', 'appointment_required', 'trailer_pool_location', 'lat', 'lon', 'location'], 'required'],
            [['state_id', 'office_id', 'bill_to'], 'default', 'value' => null],
            [['state_id', 'office_id', 'bill_to'], 'integer'],
            [['notes', 'directions', 'location'], 'string'],
            [['appointment_required', 'trailer_pool_location'], 'boolean'],
            [['lat', 'lon'], 'number'],
            [['marked_as_down'], 'safe'],
            [['company_name', 'location_name', 'address', 'city', 'main_phone', 'main_800', 'main_fax', 'contact', 'website', 'emergency', 'business_hours', 'zone', 'time_zone'], 'string', 'max' => 255],
            [['zip'], 'string', 'max' => 10],
            [['bill_to'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Customer::className(), 'targetAttribute' => ['bill_to' => 'id']],
            [['office_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Office::className(), 'targetAttribute' => ['office_id' => 'id']],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\State::className(), 'targetAttribute' => ['state_id' => 'id']],
            [['zone'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Zone::className(), 'targetAttribute' => ['zone' => 'code']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'company_name' => Yii::t('app', 'Company Name'),
            'location_name' => Yii::t('app', 'Location Name'),
            'address' => Yii::t('app', 'Address'),
            'city' => Yii::t('app', 'City'),
            'state_id' => Yii::t('app', 'State ID'),
            'zip' => Yii::t('app', 'Zip'),
            'main_phone' => Yii::t('app', 'Main Phone'),
            'main_800' => Yii::t('app', 'Main 800'),
            'main_fax' => Yii::t('app', 'Main Fax'),
            'office_id' => Yii::t('app', 'Office ID'),
            'contact' => Yii::t('app', 'Contact'),
            'website' => Yii::t('app', 'Website'),
            'notes' => Yii::t('app', 'Notes'),
            'appointment_required' => Yii::t('app', 'Appointment Required'),
            'trailer_pool_location' => Yii::t('app', 'Trailer Pool Location'),
            'lat' => Yii::t('app', 'Lat'),
            'lon' => Yii::t('app', 'Lon'),
            'emergency' => Yii::t('app', 'Emergency'),
            'business_hours' => Yii::t('app', 'Business Hours'),
            'zone' => Yii::t('app', 'Zone'),
            'bill_to' => Yii::t('app', 'Bill To'),
            'directions' => Yii::t('app', 'Directions'),
            'location' => Yii::t('app', 'Location'),
            'marked_as_down' => Yii::t('app', 'Marked As Down'),
            'time_zone' => Yii::t('app', 'Time Zone'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDocuments()
    {
        return $this->hasMany(\common\models\Document::className(), ['location_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadStops()
    {
        return $this->hasMany(\common\models\LoadStop::className(), ['company_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillTo()
    {
        return $this->hasOne(\common\models\Customer::className(), ['id' => 'bill_to']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffice()
    {
        return $this->hasOne(\common\models\Office::className(), ['id' => 'office_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(\common\models\State::className(), ['id' => 'state_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getZone0()
    {
        return $this->hasOne(\common\models\Zone::className(), ['code' => 'zone']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocationContacts()
    {
        return $this->hasMany(\common\models\LocationContact::className(), ['location_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrackingLogs()
    {
        return $this->hasMany(\common\models\TrackingLog::className(), ['location_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrucks()
    {
        return $this->hasMany(\common\models\Truck::className(), ['return_location_id' => 'id']);
    }




}
