<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "location_contact".
 *
 * @property integer $id
 * @property integer $location_id
 * @property string $contact_name
 * @property integer $department_id
 * @property string $direct_line
 * @property string $direct_fax
 * @property string $extension
 * @property string $alt_phone_1
 * @property string $desc_1
 * @property string $alt_phone_2
 * @property string $desc_2
 * @property string $email
 * @property string $notes
 *
 * @property \common\models\Department $department
 * @property \common\models\Location $location
 * @property string $aliasModel
 */
abstract class LocationContact extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'location_contact';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['location_id'], 'required'],
            [['location_id', 'department_id'], 'default', 'value' => null],
            [['location_id', 'department_id'], 'integer'],
            [['notes'], 'string'],
            [['contact_name', 'direct_line', 'direct_fax', 'extension', 'alt_phone_1', 'desc_1', 'alt_phone_2', 'desc_2', 'email'], 'string', 'max' => 255],
            [['department_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Department::className(), 'targetAttribute' => ['department_id' => 'id']],
            [['location_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Location::className(), 'targetAttribute' => ['location_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'location_id' => Yii::t('app', 'Location ID'),
            'contact_name' => Yii::t('app', 'Contact Name'),
            'department_id' => Yii::t('app', 'Department ID'),
            'direct_line' => Yii::t('app', 'Direct Line'),
            'direct_fax' => Yii::t('app', 'Direct Fax'),
            'extension' => Yii::t('app', 'Extension'),
            'alt_phone_1' => Yii::t('app', 'Alt Phone 1'),
            'desc_1' => Yii::t('app', 'Desc 1'),
            'alt_phone_2' => Yii::t('app', 'Alt Phone 2'),
            'desc_2' => Yii::t('app', 'Desc 2'),
            'email' => Yii::t('app', 'Email'),
            'notes' => Yii::t('app', 'Notes'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDepartment()
    {
        return $this->hasOne(\common\models\Department::className(), ['id' => 'department_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocation()
    {
        return $this->hasOne(\common\models\Location::className(), ['id' => 'location_id']);
    }




}
