<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "office".
 *
 * @property integer $id
 * @property string $office
 * @property string $city
 * @property integer $state_id
 *
 * @property \common\models\AccessorialPay[] $accessorialPays
 * @property \common\models\AccessorialRating[] $accessorialRatings
 * @property \common\models\Department[] $departments
 * @property \common\models\Driver[] $drivers
 * @property \common\models\Load[] $loads
 * @property \common\models\Location[] $locations
 * @property \common\models\State $state
 * @property \common\models\Payroll[] $payrolls
 * @property \common\models\Trailer[] $trailers
 * @property \common\models\Truck[] $trucks
 * @property \common\models\Unit[] $units
 * @property string $aliasModel
 */
abstract class Office extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'office';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['office', 'city'], 'required'],
            [['state_id'], 'default', 'value' => null],
            [['state_id'], 'integer'],
            [['office', 'city'], 'string', 'max' => 255],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\State::className(), 'targetAttribute' => ['state_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'office' => Yii::t('app', 'Office'),
            'city' => Yii::t('app', 'City'),
            'state_id' => Yii::t('app', 'State ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccessorialPays()
    {
        return $this->hasMany(\common\models\AccessorialPay::className(), ['office_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccessorialRatings()
    {
        return $this->hasMany(\common\models\AccessorialRating::className(), ['id' => 'accessorial_rating_id'])->viaTable('{{%accessorial_pay}}', ['office_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDepartments()
    {
        return $this->hasMany(\common\models\Department::className(), ['office_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDrivers()
    {
        return $this->hasMany(\common\models\Driver::className(), ['office_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoads()
    {
        return $this->hasMany(\common\models\Load::className(), ['office_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocations()
    {
        return $this->hasMany(\common\models\Location::className(), ['office_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(\common\models\State::className(), ['id' => 'state_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayrolls()
    {
        return $this->hasMany(\common\models\Payroll::className(), ['office_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrailers()
    {
        return $this->hasMany(\common\models\Trailer::className(), ['office_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrucks()
    {
        return $this->hasMany(\common\models\Truck::className(), ['office_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUnits()
    {
        return $this->hasMany(\common\models\Unit::className(), ['office_id' => 'id']);
    }




}
