<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "payroll_pay".
 *
 * @property integer $id
 * @property integer $payroll_id
 * @property integer $d_load_id
 * @property string $created_at
 * @property integer $created_by
 *
 * @property \common\models\Load $dLoad
 * @property \common\models\Payroll $payroll
 * @property \common\models\User $createdBy
 * @property string $aliasModel
 */
abstract class PayrollPay extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'payroll_pay';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['payroll_id'], 'required'],
            [['payroll_id', 'd_load_id'], 'default', 'value' => null],
            [['payroll_id', 'd_load_id'], 'integer'],
            [['d_load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['d_load_id' => 'id']],
            [['payroll_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Payroll::className(), 'targetAttribute' => ['payroll_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['created_by' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'payroll_id' => Yii::t('app', 'Payroll ID'),
            'd_load_id' => Yii::t('app', 'D Load ID'),
            'created_at' => Yii::t('app', 'Created At'),
            'created_by' => Yii::t('app', 'Created By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDLoad()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'd_load_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayroll()
    {
        return $this->hasOne(\common\models\Payroll::className(), ['id' => 'payroll_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'created_by']);
    }




}
