<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "purchase_order_codes".
 *
 * @property string $code
 * @property string $account_id
 * @property string $description
 * @property string $type
 *
 * @property \common\models\Account $account
 * @property string $aliasModel
 */
abstract class PurchaseOrderCode extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'purchase_order_code';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code', 'account_id', 'type'], 'required'],
            [['code', 'account_id'], 'string', 'max' => 4],
            [['description', 'type'], 'string', 'max' => 255],
            [['code'], 'unique'],
            [['account_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Account::className(), 'targetAttribute' => ['account_id' => 'account']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'code' => Yii::t('app', 'Code'),
            'account_id' => Yii::t('app', 'Account ID'),
            'description' => Yii::t('app', 'Description'),
            'type' => Yii::t('app', 'Type'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccount()
    {
        return $this->hasOne(\common\models\Account::className(), ['account' => 'account_id']);
    }




}
