<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "report_media".
 *
 * @property integer $id
 * @property integer $report_id
 * @property string $side
 * @property boolean $is_major
 * @property boolean $is_interior
 * @property string $description
 * @property string $mime_type
 * @property string $file
 * @property integer $width
 * @property integer $height
 * @property integer $size
 * @property string $damage_type
 * @property integer $category_id
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 *
 * @property \common\models\Report $report
 * @property \common\models\ReportMediaCategory $category
 * @property \common\models\User $createdBy
 * @property \common\models\User $updatedBy
 * @property string $aliasModel
 */
abstract class ReportMedia extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'report_media';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['report_id', 'side', 'is_major', 'is_interior', 'mime_type', 'file'], 'required'],
            [['report_id', 'width', 'height', 'size', 'category_id'], 'default', 'value' => null],
            [['report_id', 'width', 'height', 'size', 'category_id'], 'integer'],
            [['is_major', 'is_interior'], 'boolean'],
            [['side', 'description', 'mime_type', 'file', 'damage_type'], 'string', 'max' => 255],
            [['report_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Report::className(), 'targetAttribute' => ['report_id' => 'id']],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\ReportMediaCategory::className(), 'targetAttribute' => ['category_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['updated_by' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'report_id' => Yii::t('app', 'Report ID'),
            'side' => Yii::t('app', 'Side'),
            'is_major' => Yii::t('app', 'Is Major'),
            'is_interior' => Yii::t('app', 'Is Interior'),
            'description' => Yii::t('app', 'Description'),
            'mime_type' => Yii::t('app', 'Mime Type'),
            'file' => Yii::t('app', 'File'),
            'width' => Yii::t('app', 'Width'),
            'height' => Yii::t('app', 'Height'),
            'size' => Yii::t('app', 'Size'),
            'damage_type' => Yii::t('app', 'Damage Type'),
            'created_at' => Yii::t('app', 'Created At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'category_id' => Yii::t('app', 'Category ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReport()
    {
        return $this->hasOne(\common\models\Report::className(), ['id' => 'report_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(\common\models\ReportMediaCategory::className(), ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'updated_by']);
    }




}
