<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "trailer_type".
 *
 * @property string $type
 * @property integer $height
 * @property integer $length
 * @property string $description
 *
 * @property \common\models\Trailer[] $trailers
 * @property string $aliasModel
 */
abstract class TrailerType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'trailer_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'height', 'length'], 'required'],
            [['height', 'length'], 'default', 'value' => null],
            [['height', 'length'], 'integer'],
            [['type', 'description'], 'string', 'max' => 255],
            [['type'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'type' => Yii::t('app', 'Type'),
            'height' => Yii::t('app', 'Height'),
            'length' => Yii::t('app', 'Length'),
            'description' => Yii::t('app', 'Description'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrailers()
    {
        return $this->hasMany(\common\models\Trailer::className(), ['type' => 'type']);
    }




}
