<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "truck_type".
 *
 * @property string $type
 * @property string $description
 * @property integer $max_weight
 * @property integer $axles
 * @property integer $height
 *
 * @property \common\models\Truck[] $trucks
 * @property string $aliasModel
 */
abstract class TruckType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'truck_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type'], 'required'],
            [['max_weight', 'axles', 'height'], 'default', 'value' => null],
            [['max_weight', 'axles', 'height'], 'integer'],
            [['type', 'description'], 'string', 'max' => 255],
            [['type'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'type' => Yii::t('app', 'Type'),
            'description' => Yii::t('app', 'Description'),
            'max_weight' => Yii::t('app', 'Max Weight'),
            'axles' => Yii::t('app', 'Axles'),
            'height' => Yii::t('app', 'Height'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrucks()
    {
        return $this->hasMany(\common\models\Truck::className(), ['type' => 'type']);
    }




}
