<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "user".
 *
 * @property integer $id
 * @property string $auth_key
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property integer $status
 * @property string $verification_token
 * @property integer $department_id
 * @property string $last_name
 * @property string $first_name
 * @property string $scope
 * @property integer $default_office_id
 * @property boolean $agent_and_subject_to_agent_rules
 * @property boolean $can_access_dispatch_data_from_all_offices
 * @property string $last_session_id
 * @property string $last_activity
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \common\models\AccountingDefault[] $accountingDefaults
 * @property \common\models\AccountingDefault[] $accountingDefaults0
 * @property \common\models\Bill[] $bills
 * @property \common\models\Bill[] $bills0
 * @property \common\models\BillItem[] $billItems
 * @property \common\models\BillItem[] $billItems0
 * @property \common\models\ChatMessage[] $chatMessages
 * @property \common\models\ChatMessage[] $chatMessages0
 * @property \common\models\ChatMessageSeen[] $chatMessageSeens
 * @property \common\models\ChatMessage[] $messages
 * @property \common\models\Company[] $companies
 * @property \common\models\Company[] $companies0
 * @property \common\models\Department[] $departments
 * @property \common\models\Department[] $departments0
 * @property \common\models\Device[] $devices
 * @property \common\models\DispatchAssignment[] $dispatchAssignments
 * @property \common\models\DispatchAssignment[] $dispatchAssignments0
 * @property \common\models\Document[] $documents
 * @property \common\models\Document[] $documents0
 * @property \common\models\Driver $driver
 * @property \common\models\DriverAdjustment[] $driverAdjustments
 * @property \common\models\DriverAdjustment[] $driverAdjustments0
 * @property \common\models\DriverCompliance[] $driverCompliances
 * @property \common\models\DriverCompliance[] $driverCompliances0
 * @property \common\models\FuelPurchase[] $fuelPurchases
 * @property \common\models\FuelPurchase[] $fuelPurchases0
 * @property \common\models\Load[] $loads
 * @property \common\models\Load[] $loads0
 * @property \common\models\Load[] $loads1
 * @property \common\models\LoadDrop[] $loadDrops
 * @property \common\models\LoadDrop[] $loadDrops0
 * @property \common\models\LoadMovement[] $loadMovements
 * @property \common\models\LoadMovement[] $loadMovements0
 * @property \common\models\LoadNote[] $loadNotes
 * @property \common\models\LoadStop[] $loadStops
 * @property \common\models\LoadStop[] $loadStops0
 * @property \common\models\Payment[] $payments
 * @property \common\models\PaymentTermCode[] $paymentTermCodes
 * @property \common\models\PaymentTermCode[] $paymentTermCodes0
 * @property \common\models\PayrollAdjustment[] $payrollAdjustments
 * @property \common\models\PayrollAdjustment[] $payrollAdjustments0
 * @property \common\models\PayrollBatch[] $payrollBatches
 * @property \common\models\PayrollBatch[] $payrollBatches0
 * @property \common\models\PayrollPay[] $payrollPays
 * @property \common\models\ReportMedia[] $reportMedia
 * @property \common\models\ReportMedia[] $reportMedia0
 * @property \common\models\ReportMediaCategory[] $reportMediaCategories
 * @property \common\models\ReportMediaCategory[] $reportMediaCategories0
 * @property \common\models\Setting[] $settings
 * @property \common\models\TrackingLog[] $trackingLogs
 * @property \common\models\TrackingLog[] $trackingLogs0
 * @property \common\models\Truck[] $trucks
 * @property \common\models\TruckOdometer[] $truckOdometers
 * @property \common\models\TruckOdometer[] $truckOdometers0
 * @property \common\models\Unit[] $units
 * @property \common\models\Unit[] $units0
 * @property \common\models\Department $department
 * @property \common\models\Office $defaultOffice
 * @property \common\models\WorkOrder[] $workOrders
 * @property \common\models\WorkOrder[] $workOrders0
 * @property \common\models\WorkOrderService[] $workOrderServices
 * @property \common\models\WorkOrderService[] $workOrderServices0
 * @property string $aliasModel
 */
abstract class User extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['auth_key', 'password_hash', 'email'], 'required'],
            [['status', 'department_id', 'default_office_id'], 'default', 'value' => null],
            [['status', 'department_id', 'default_office_id'], 'integer'],
            [['agent_and_subject_to_agent_rules', 'can_access_dispatch_data_from_all_offices'], 'boolean'],
            [['last_activity'], 'safe'],
            [['auth_key', 'last_session_id'], 'string', 'max' => 32],
            [['password_hash', 'password_reset_token', 'email', 'verification_token', 'last_name', 'first_name', 'scope'], 'string', 'max' => 255],
            [['email'], 'unique'],
            [['password_reset_token'], 'unique'],
            [['department_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Department::className(), 'targetAttribute' => ['department_id' => 'id']],
            [['default_office_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Office::className(), 'targetAttribute' => ['default_office_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'auth_key' => Yii::t('app', 'Auth Key'),
            'password_hash' => Yii::t('app', 'Password Hash'),
            'password_reset_token' => Yii::t('app', 'Password Reset Token'),
            'email' => Yii::t('app', 'Email'),
            'status' => Yii::t('app', 'Status'),
            'verification_token' => Yii::t('app', 'Verification Token'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'department_id' => Yii::t('app', 'Department ID'),
            'last_name' => Yii::t('app', 'Last Name'),
            'first_name' => Yii::t('app', 'First Name'),
            'scope' => Yii::t('app', 'Scope'),
            'default_office_id' => Yii::t('app', 'Default Office ID'),
            'agent_and_subject_to_agent_rules' => Yii::t('app', 'Agent And Subject To Agent Rules'),
            'can_access_dispatch_data_from_all_offices' => Yii::t('app', 'Can Access Dispatch Data From All Offices'),
            'last_session_id' => Yii::t('app', 'Last Session ID'),
            'last_activity' => Yii::t('app', 'Last Activity'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccountingDefaults()
    {
        return $this->hasMany(\common\models\AccountingDefault::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccountingDefaults0()
    {
        return $this->hasMany(\common\models\AccountingDefault::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBills()
    {
        return $this->hasMany(\common\models\Bill::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBills0()
    {
        return $this->hasMany(\common\models\Bill::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillItems()
    {
        return $this->hasMany(\common\models\BillItem::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillItems0()
    {
        return $this->hasMany(\common\models\BillItem::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChatMessages()
    {
        return $this->hasMany(\common\models\ChatMessage::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChatMessages0()
    {
        return $this->hasMany(\common\models\ChatMessage::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChatMessageSeens()
    {
        return $this->hasMany(\common\models\ChatMessageSeen::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMessages()
    {
        return $this->hasMany(\common\models\ChatMessage::className(), ['id' => 'message_id'])->viaTable('{{%chat_message_seen}}', ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompanies()
    {
        return $this->hasMany(\common\models\Company::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompanies0()
    {
        return $this->hasMany(\common\models\Company::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDepartments()
    {
        return $this->hasMany(\common\models\Department::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDepartments0()
    {
        return $this->hasMany(\common\models\Department::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDevices()
    {
        return $this->hasMany(\common\models\Device::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDispatchAssignments()
    {
        return $this->hasMany(\common\models\DispatchAssignment::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDispatchAssignments0()
    {
        return $this->hasMany(\common\models\DispatchAssignment::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDocuments()
    {
        return $this->hasMany(\common\models\Document::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDocuments0()
    {
        return $this->hasMany(\common\models\Document::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDriver()
    {
        return $this->hasOne(\common\models\Driver::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDriverAdjustments()
    {
        return $this->hasMany(\common\models\DriverAdjustment::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDriverAdjustments0()
    {
        return $this->hasMany(\common\models\DriverAdjustment::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDriverCompliances()
    {
        return $this->hasMany(\common\models\DriverCompliance::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDriverCompliances0()
    {
        return $this->hasMany(\common\models\DriverCompliance::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFuelPurchases()
    {
        return $this->hasMany(\common\models\FuelPurchase::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFuelPurchases0()
    {
        return $this->hasMany(\common\models\FuelPurchase::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoads()
    {
        return $this->hasMany(\common\models\Load::className(), ['booked_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoads0()
    {
        return $this->hasMany(\common\models\Load::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoads1()
    {
        return $this->hasMany(\common\models\Load::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadDrops()
    {
        return $this->hasMany(\common\models\LoadDrop::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadDrops0()
    {
        return $this->hasMany(\common\models\LoadDrop::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadMovements()
    {
        return $this->hasMany(\common\models\LoadMovement::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadMovements0()
    {
        return $this->hasMany(\common\models\LoadMovement::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadNotes()
    {
        return $this->hasMany(\common\models\LoadNote::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadStops()
    {
        return $this->hasMany(\common\models\LoadStop::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadStops0()
    {
        return $this->hasMany(\common\models\LoadStop::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayments()
    {
        return $this->hasMany(\common\models\Payment::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPaymentTermCodes()
    {
        return $this->hasMany(\common\models\PaymentTermCode::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPaymentTermCodes0()
    {
        return $this->hasMany(\common\models\PaymentTermCode::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayrollAdjustments()
    {
        return $this->hasMany(\common\models\PayrollAdjustment::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayrollAdjustments0()
    {
        return $this->hasMany(\common\models\PayrollAdjustment::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayrollBatches()
    {
        return $this->hasMany(\common\models\PayrollBatch::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayrollBatches0()
    {
        return $this->hasMany(\common\models\PayrollBatch::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayrollPays()
    {
        return $this->hasMany(\common\models\PayrollPay::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReportMedia()
    {
        return $this->hasMany(\common\models\ReportMedia::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReportMedia0()
    {
        return $this->hasMany(\common\models\ReportMedia::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReportMediaCategories()
    {
        return $this->hasMany(\common\models\ReportMediaCategory::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReportMediaCategories0()
    {
        return $this->hasMany(\common\models\ReportMediaCategory::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSettings()
    {
        return $this->hasMany(\common\models\Setting::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrackingLogs()
    {
        return $this->hasMany(\common\models\TrackingLog::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrackingLogs0()
    {
        return $this->hasMany(\common\models\TrackingLog::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrucks()
    {
        return $this->hasMany(\common\models\Truck::className(), ['downed_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTruckOdometers()
    {
        return $this->hasMany(\common\models\TruckOdometer::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTruckOdometers0()
    {
        return $this->hasMany(\common\models\TruckOdometer::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUnits()
    {
        return $this->hasMany(\common\models\Unit::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUnits0()
    {
        return $this->hasMany(\common\models\Unit::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDepartment()
    {
        return $this->hasOne(\common\models\Department::className(), ['id' => 'department_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDefaultOffice()
    {
        return $this->hasOne(\common\models\Office::className(), ['id' => 'default_office_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkOrders()
    {
        return $this->hasMany(\common\models\WorkOrder::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkOrders0()
    {
        return $this->hasMany(\common\models\WorkOrder::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkOrderServices()
    {
        return $this->hasMany(\common\models\WorkOrderService::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkOrderServices0()
    {
        return $this->hasMany(\common\models\WorkOrderService::className(), ['updated_by' => 'id']);
    }




}
