<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "vehicle_service_code".
 *
 * @property string $code
 * @property string $equip
 * @property integer $days
 * @property integer $miles
 * @property string $description
 * @property string $aliasModel
 */
abstract class VehicleServiceCode extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vehicle_service_code';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code', 'equip'], 'required'],
            [['days', 'miles'], 'default', 'value' => null],
            [['days', 'miles'], 'integer'],
            [['code', 'equip', 'description'], 'string', 'max' => 255],
            [['code'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'code' => Yii::t('app', 'Code'),
            'equip' => Yii::t('app', 'Equip'),
            'days' => Yii::t('app', 'Days'),
            'miles' => Yii::t('app', 'Miles'),
            'description' => Yii::t('app', 'Description'),
        ];
    }




}
