<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "vendor".
 *
 * @property integer $id
 * @property string $notes
 * @property string $name
 * @property string $address_1
 * @property string $address_2
 * @property string $city
 * @property integer $state_id
 * @property string $zip
 * @property string $main_phone
 * @property string $main_800
 * @property string $main_fax
 * @property string $email
 * @property string $website
 * @property string $ar_contact
 * @property string $other_contact
 * @property string $account_no
 * @property boolean $mail_list
 * @property string $marked_as_down
 * @property integer $updated_by
 * @property string $updated_at
 * @property integer $created_by
 * @property string $created_at
 *
 * @property \common\models\Document[] $documents
 * @property \common\models\Driver[] $drivers
 * @property \common\models\Truck[] $trucks
 * @property \common\models\State $state
 * @property \common\models\VendorContact[] $vendorContacts
 * @property \common\models\VendorContactNote[] $vendorContactNotes
 * @property string $aliasModel
 */
abstract class Vendor extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vendor';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['notes'], 'string'],
            [['name', 'mail_list'], 'required'],
            [['state_id'], 'default', 'value' => null],
            [['state_id'], 'integer'],
            [['mail_list'], 'boolean'],
            [['marked_as_down'], 'safe'],
            [['name', 'address_1', 'address_2', 'city', 'main_phone', 'main_800', 'main_fax', 'email', 'website', 'ar_contact', 'other_contact', 'account_no'], 'string', 'max' => 255],
            [['zip'], 'string', 'max' => 10],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\State::className(), 'targetAttribute' => ['state_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'notes' => Yii::t('app', 'Notes'),
            'name' => Yii::t('app', 'Name'),
            'address_1' => Yii::t('app', 'Address 1'),
            'address_2' => Yii::t('app', 'Address 2'),
            'city' => Yii::t('app', 'City'),
            'state_id' => Yii::t('app', 'State ID'),
            'zip' => Yii::t('app', 'Zip'),
            'main_phone' => Yii::t('app', 'Main Phone'),
            'main_800' => Yii::t('app', 'Main 800'),
            'main_fax' => Yii::t('app', 'Main Fax'),
            'email' => Yii::t('app', 'Email'),
            'website' => Yii::t('app', 'Website'),
            'ar_contact' => Yii::t('app', 'Ar Contact'),
            'other_contact' => Yii::t('app', 'Other Contact'),
            'account_no' => Yii::t('app', 'Account No'),
            'mail_list' => Yii::t('app', 'Mail List'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_at' => Yii::t('app', 'Created At'),
            'marked_as_down' => Yii::t('app', 'Marked As Down'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDocuments()
    {
        return $this->hasMany(\common\models\Document::className(), ['vendor_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDrivers()
    {
        return $this->hasMany(\common\models\Driver::className(), ['pay_to_vendor_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrucks()
    {
        return $this->hasMany(\common\models\Truck::className(), ['owned_by_vendor_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(\common\models\State::className(), ['id' => 'state_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendorContacts()
    {
        return $this->hasMany(\common\models\VendorContact::className(), ['vendor_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendorContactNotes()
    {
        return $this->hasMany(\common\models\VendorContactNote::className(), ['vendor_id' => 'id']);
    }




}
