<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "violation_message".
 *
 * @property integer $id
 * @property string $log_violation_warning_letter_text
 * @property string $log_violation_disciplinary_letter_text
 * @property string $created_at
 * @property string $aliasModel
 */
abstract class ViolationMessage extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'violation_message';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['log_violation_warning_letter_text', 'log_violation_disciplinary_letter_text'], 'string'],
            [['created_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'log_violation_warning_letter_text' => Yii::t('app', 'Log Violation Warning Letter Text'),
            'log_violation_disciplinary_letter_text' => Yii::t('app', 'Log Violation Disciplinary Letter Text'),
            'created_at' => Yii::t('app', 'Created At'),
        ];
    }




}
