#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER $DATABASE_USER WITH PASSWORD '$DATABASE_PASSWORD';
CREATE DATABASE $DATABASE_DB TEMPLATE=template_postgis;
GRANT ALL PRIVILEGES ON DATABASE $DATABASE_DB TO $DATABASE_USER;
CREATE USER $DATABASE_USER_TEST WITH PASSWORD '$DATABASE_PASSWORD_TEST';
CREATE DATABASE $DATABASE_DB_TEST TEMPLATE=template_postgis;
GRANT ALL PRIVILEGES ON DATABASE $DATABASE_DB_TEST TO $DATABASE_USER_TEST;
EOSQL
