<?php
/**
 * /var/www/html/frontend/runtime/giiant/d4b4964a63cc95065fa0ae19074007ee
 *
 * @package default
 */


use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\bootstrap4\Tabs;

/**
 *
 * @var yii\web\View $this
 * @var common\models\Location $model
 */
$copyParams = $model->attributes;

$this->title = Yii::t('app', 'Location');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Locations'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>
<div class="giiant-crud location-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?php echo \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?php echo Yii::t('app', 'Location') ?>
        <small>
            <?php echo Html::encode($model->id) ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='float-left'>
            <?php echo Html::a(
	'<i class="fa fa-edit"></i> ' . Yii::t('app', 'Edit'),
	[ 'update', 'id' => $model->id],
	['class' => 'btn btn-sm btn-secondary']) ?>

            <?php echo Html::a(
	'<i class="fa fa-copy"></i> ' . Yii::t('app', 'Copy'),
	['create', 'id' => $model->id, 'Location'=>$copyParams],
	['class' => 'btn btn-sm btn-secondary']) ?>

            <?php echo Html::a(
	'<i class="fa fa-plus"></i> ' . Yii::t('app', 'New'),
	['create'],
	['class' => 'btn btn-sm btn-secondary']) ?>
        </div>

        <div class="float-right">
            <?php echo Html::a('<i class="fa fa-list"></i> '
	. Yii::t('app', 'Full list'), ['index'], ['class'=>'btn btn-sm btn-secondary']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('common\models\Location'); ?>


    <?php echo DetailView::widget([
		'model' => $model,
		'attributes' => [
			'company_name',
			'location_name',
			'address',
			'city',
			'zip',
			'main_phone',
			'contact',
			'appointment_required:boolean',
			'trailer_pool_location:boolean',
			'lat',
			'lon',
			'emergency',
			'location',
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'state_id',
				'value' => ($model->state ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['state/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->state->_label, ['state/view', 'id' => $model->state->id, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Location'=>['state_id' => $model->state_id]])
					:
					'<span class="label label-warning">?</span>'),
			],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'office_id',
				'value' => ($model->office ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['office/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->office->_label, ['office/view', 'id' => $model->office->id, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Location'=>['office_id' => $model->office_id]])
					:
					'<span class="label label-warning">?</span>'),
			],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'bill_to',
				'value' => ($model->billTo ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['customer/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->billTo->name, ['customer/view', 'id' => $model->billTo->id, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Location'=>['bill_to' => $model->bill_to]])
					:
					'<span class="label label-warning">?</span>'),
			],
			'notes:ntext',
			'directions:ntext',
			'main_800',
			'main_fax',
			'website',
			'business_hours',
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'zone',
				'value' => ($model->zone0 ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['zone/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->zone0->code, ['zone/view', 'code' => $model->zone0->code, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Location'=>['zone' => $model->zone]])
					:
					'<span class="label label-warning">?</span>'),
			],
		],
	]); ?>


    <hr/>

    <?php echo Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Delete'), ['delete', 'id' => $model->id],
	[
		'class' => 'btn btn-danger',
		'data-confirm' => '' . Yii::t('app', 'Are you sure to delete this item?') . '',
		'data-method' => 'post',
	]); ?>
    <?php $this->endBlock(); ?>



    <?php echo Tabs::widget(
	[
		'id' => 'relation-tabs',
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => '<b class=""># '.Html::encode($model->id).'</b>',
				'content' => $this->blocks['common\models\Location'],
				'active'  => true,
			],
		]
	]
);
?>
</div>
