<?php
/**
 * /var/www/html/frontend/runtime/giiant/d4b4964a63cc95065fa0ae19074007ee
 *
 * @package default
 */


use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\bootstrap4\Tabs;

/**
 *
 * @var yii\web\View $this
 * @var common\models\Unit $model
 */
$copyParams = $model->attributes;

$this->title = Yii::t('app', 'Unit');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Units'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'View');
?>
<div class="giiant-crud unit-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?php echo \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?php echo Yii::t('app', 'Unit') ?>
        <small>
            <?php echo Html::encode($model->id) ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='float-left'>
            <?php echo Html::a(
	'<i class="fa fa-edit"></i> ' . Yii::t('app', 'Edit'),
	[ 'update', 'id' => $model->id],
	['class' => 'btn btn-sm btn-secondary']) ?>

            <?php echo Html::a(
	'<i class="fa fa-copy"></i> ' . Yii::t('app', 'Copy'),
	['create', 'id' => $model->id, 'Unit'=>$copyParams],
	['class' => 'btn btn-sm btn-secondary']) ?>

            <?php echo Html::a(
	'<i class="fa fa-plus"></i> ' . Yii::t('app', 'New'),
	['create'],
	['class' => 'btn btn-sm btn-secondary']) ?>
        </div>

        <div class="float-right">
            <?php echo Html::a('<i class="fa fa-list"></i> '
	. Yii::t('app', 'Full list'), ['index'], ['class'=>'btn btn-sm btn-secondary']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('common\models\Unit'); ?>


    <?php echo DetailView::widget([
		'model' => $model,
		'attributes' => [
			'active',
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'driver_id',
				'value' => ($model->driver ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['driver/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->driver->id, ['driver/view', 'id' => $model->driver->id, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Unit'=>['driver_id' => $model->driver_id]])
					:
					'<span class="label label-warning">?</span>'),
			],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'co_driver_id',
				'value' => ($model->coDriver ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['driver/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->coDriver->id, ['driver/view', 'id' => $model->coDriver->id, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Unit'=>['co_driver_id' => $model->co_driver_id]])
					:
					'<span class="label label-warning">?</span>'),
			],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'truck_id',
				'value' => ($model->truck ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['truck/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->truck->id, ['truck/view', 'id' => $model->truck->id, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Unit'=>['truck_id' => $model->truck_id]])
					:
					'<span class="label label-warning">?</span>'),
			],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'trailer_id',
				'value' => ($model->trailer ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['trailer/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->trailer->id, ['trailer/view', 'id' => $model->trailer->id, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Unit'=>['trailer_id' => $model->trailer_id]])
					:
					'<span class="label label-warning">?</span>'),
			],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'trailer_2_id',
				'value' => ($model->trailer2 ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['trailer/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->trailer2->id, ['trailer/view', 'id' => $model->trailer2->id, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Unit'=>['trailer_2_id' => $model->trailer_2_id]])
					:
					'<span class="label label-warning">?</span>'),
			],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'office_id',
				'value' => ($model->office ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['office/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->office->_label, ['office/view', 'id' => $model->office->id, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Unit'=>['office_id' => $model->office_id]])
					:
					'<span class="label label-warning">?</span>'),
			],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'updated_by',
				'value' => ($model->updatedBy ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['user/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->updatedBy->id, ['user/view', 'id' => $model->updatedBy->id, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Unit'=>['updated_by' => $model->updated_by]])
					:
					'<span class="label label-warning">?</span>'),
			],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'created_by',
				'value' => ($model->createdBy ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['user/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->createdBy->id, ['user/view', 'id' => $model->createdBy->id, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Unit'=>['created_by' => $model->created_by]])
					:
					'<span class="label label-warning">?</span>'),
			],
		],
	]); ?>


    <hr/>

    <?php echo Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Delete'), ['delete', 'id' => $model->id],
	[
		'class' => 'btn btn-danger',
		'data-confirm' => '' . Yii::t('app', 'Are you sure to delete this item?') . '',
		'data-method' => 'post',
	]); ?>
    <?php $this->endBlock(); ?>



    <?php echo Tabs::widget(
	[
		'id' => 'relation-tabs',
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => '<b class=""># '.Html::encode($model->id).'</b>',
				'content' => $this->blocks['common\models\Unit'],
				'active'  => true,
			],
		]
	]
);
?>
</div>
