<?php
/**
 * /var/www/html/backend/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 *
 * @var yii\web\View $this
 * @var common\models\AccessorialRating $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="accessorial-rating-form">

    <?php $form = ActiveForm::begin([
		'id' => 'AccessorialRating',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-danger',
		'fieldConfig' => [
			'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
			'horizontalCssClasses' => [
				'label' => 'col-sm-2',
				//'offset' => 'col-sm-offset-4',
				'wrapper' => 'col-sm-8',
				'error' => '',
				'hint' => '',
			],
		],
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


<!-- attribute accessorial_rating_matrix -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'accessorial_rating_matrix')->dropDownList(
	\yii\helpers\ArrayHelper::map(common\models\AccessorialMatrix::find()->all(), 'matrix_no', '_label'),
	[
		'prompt' => Yii::t('app', 'Select'),
		'disabled' => (isset($relAttributes) && isset($relAttributes['accessorial_rating_matrix'])),
	]
); ?>

<!-- attribute description -->
			<?php echo $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

<!-- attribute gl_account -->
			<?php echo $form->field($model, 'gl_account')->textInput() ?>

<!-- attribute rate -->
			<?php echo $form->field($model, 'rate')->textInput() ?>

<!-- attribute pay_driver -->
			<?php echo $form->field($model, 'pay_driver')->checkbox() ?>

<!-- attribute pay_comm -->
			<?php echo $form->field($model, 'pay_comm')->checkbox() ?>

<!-- attribute auto -->
			<?php echo $form->field($model, 'auto')->checkbox() ?>

<!-- attribute inactive -->
			<?php echo $form->field($model, 'inactive')->checkbox() ?>
        </p>
        <?php $this->endBlock(); ?>

        <?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => Yii::t('app', 'AccessorialRating'),
				'content' => $this->blocks['main'],
				'active'  => true,
			],
		]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
