<?php
/**
 * /var/www/html/backend/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
 *
 * @var yii\web\View $this
 * @var common\models\Commodity $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="commodity-form">

    <?php $form = ActiveForm::begin([
		'id' => 'Commodity',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-danger',
		'fieldConfig' => [
			'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
			'horizontalCssClasses' => [
				'label' => 'col-sm-2',
				//'offset' => 'col-sm-offset-4',
				'wrapper' => 'col-sm-8',
				'error' => '',
				'hint' => '',
			],
		],
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


<!-- attribute description -->
			<?php echo $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

<!-- attribute hazmat_code -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'hazmat_code')->dropDownList(
	\yii\helpers\ArrayHelper::map(common\models\Hazmat::find()->all(), 'code', 'code'),
	[
		'prompt' => Yii::t('app', 'Select'),
		'disabled' => (isset($relAttributes) && isset($relAttributes['hazmat_code'])),
	]
); ?>

<!-- attribute class -->
			<?php echo $form->field($model, 'class')->textInput(['maxlength' => true]) ?>

<!-- attribute type -->
            <?= $form->field($model, 'type')->dropDownList(\common\enums\CommodityType::getUiEnums(false), ['prompt' => Yii::t('app', 'Select')]) ?>
        </p>
        <?php $this->endBlock(); ?>

        <?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => Yii::t('app', 'Commodity'),
				'content' => $this->blocks['main'],
				'active'  => true,
			],
		]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
